import { calculateProject, defaultProject } from './calculations.js'
import { buildCandidates, productRows } from './selection.js'

const $=s=>document.querySelector(s)
const app=$('#app')
const clone=x=>JSON.parse(JSON.stringify(x))
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const f=(v,d=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d})
const now=()=>new Date().toISOString()
const uid=(p='id')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`
const storage={project:'blowerfit.currentProject.v1',reports:'blowerfit.savedReports.v1',theme:'blowerfit.theme.v1',favorites:'blowerfit.favorites.v1'}
const REPORT_DEFAULTS={candidate:true,pipeSchedule:true,formulas:false,inputSummary:false,environment:false,warnings:true,sources:false,suppliers:false}
function ensureProject(p){const out=p&&typeof p==='object'?p:defaultProject();out.reportOptions={...REPORT_DEFAULTS,...(out.reportOptions||{})};return out}
const load=(k,fb)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):fb}catch{return fb}}
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}

let DATA=null
let state={
  route:'selector', project:ensureProject(load(storage.project,null)||defaultProject()), calc:null, calcStamp:null,
  reports:load(storage.reports,[]), favorites:load(storage.favorites,[]), theme:localStorage.getItem(storage.theme)||'system',
  productFilters:{q:'',type:'',manufacturer:'',minKw:0,maxKw:500,minFlow:0,minPressure:0,frequency:60,koreaOnly:true}, compareIds:[], compareOpen:false, supplierQuery:'', toast:null
}

function decodeShared(){const q=new URLSearchParams(location.search).get('state');if(!q)return null;try{const n=q.replaceAll('-','+').replaceAll('_','/'),pad=n+'='.repeat((4-n.length%4)%4),bin=atob(pad),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch{return null}}
function encodeShared(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function readRoute(){const r=location.hash.replace(/^#\/?/,'').split('?')[0];return['selector','products','suppliers','guide','reports'].includes(r)?r:'selector'}
function setTheme(t){state.theme=t;localStorage.setItem(storage.theme,t);const mq=matchMedia('(prefers-color-scheme:dark)');document.documentElement.dataset.theme=t==='system'?(mq.matches?'dark':'light'):t}
setTheme(state.theme)

async function init(){
  try{
    DATA=await fetch('./data/blower_webservice_seed.json').then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()})
    const shared=decodeShared();if(shared){state.project=ensureProject(shared);save(storage.project,state.project)}
    state.route=readRoute();state.calc=calculateProject(state.project);state.calcStamp=state.project.updatedAt;render()
    window.addEventListener('hashchange',()=>{state.route=readRoute();render();scrollTo({top:0,behavior:'smooth'})})
    if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}),{once:true})
  }catch(err){app.innerHTML=`<main class="fatal"><h1>데이터를 불러오지 못했습니다.</h1><p>${esc(err.message)}</p><button onclick="location.reload()">다시 시도</button></main>`}
}

const iconMark=`<span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="20"/><path d="M24 8c7 3 9 9 6 14-2 4-7 6-11 4 1-7 2-13 5-18Zm-14 20c1-7 6-10 12-9 4 1 7 5 7 9-6 3-12 4-19 0Zm26 9c-6 4-12 2-15-3-2-4-1-8 3-11 6 3 10 7 12 14Z"/></svg></span>`
const navs=[['selector','선정 계산기','계산','⌁'],['products','제품 DB','제품','▦'],['suppliers','구매처','구매','◎'],['guide','기술 가이드','가이드','?'],['reports','저장 리포트','리포트','▤']]
function topReportMenu(){return `<details class="top-report-menu"><summary class="btn btn-secondary">결과 / 저장 ▾</summary><div class="top-report-popover"><div class="top-report-jumps"><button data-action="scroll-results">결과 요약</button><button data-action="scroll-candidates">선정 후보</button><button data-action="scroll-pipes">배관표</button><button data-action="scroll-formulas">계산식</button></div><div class="top-report-divider"></div><button data-action="report-settings">보고서 구성…</button><button data-action="export-pdf">PDF 저장</button><button data-action="export-png">PNG 이미지</button><button data-action="export-html">HTML 문서</button><button data-action="export-json">JSON 데이터</button><button data-action="print">인쇄</button></div></details>`}
function shell(content){const themeLabel=state.theme==='system'?'시스템':state.theme==='light'?'라이트':'다크';return `<div class="app-shell"><header class="topbar"><button class="brand" data-route="selector">${iconMark}<span><strong>BlowerFit KR</strong><small>Industrial Blower Engineering</small></span></button><nav class="desktop-nav">${navs.map(n=>`<button data-route="${n[0]}" class="${state.route===n[0]?'active':''}">${n[1]}</button>`).join('')}</nav><div class="top-actions">${state.route==='selector'?topReportMenu():''}<button class="btn btn-ghost" data-action="theme">${state.theme==='dark'?'☾':state.theme==='light'?'☀':'◐'} <span class="theme-text">${themeLabel}</span></button></div></header><nav class="mobile-nav">${navs.map(n=>`<button data-route="${n[0]}" class="${state.route===n[0]?'active':''}"><span>${n[3]}</span>${n[2]}</button>`).join('')}</nav>${content}<footer><div><b>BlowerFit KR</b><span>산업용 블로워 예비 선정 · 배관 사이징 · 모델/구매처 연결</span></div><div><span>© ${new Date().getFullYear()}</span><button data-route="guide">기술/책임 범위</button></div></footer>${state.toast?`<div class="toast" role="status">${esc(state.toast)}</div>`:''}${state.compareOpen?compareModal():''}</div>`}
function render(){if(!DATA)return;let page=state.route==='selector'?selectorPage():state.route==='products'?productsPage():state.route==='suppliers'?suppliersPage():state.route==='guide'?guidePage():reportsPage();app.innerHTML=shell(page)}
function toast(msg){state.toast=msg;const old=$('.toast');if(old)old.remove();document.body.insertAdjacentHTML('beforeend',`<div class="toast" role="status">${esc(msg)}</div>`);setTimeout(()=>{state.toast=null;$('.toast')?.remove()},3000)}

function btn(label,action,variant='primary',extra=''){return `<button class="btn btn-${variant}" data-action="${action}" ${extra}>${label}</button>`}
function badge(text,tone='neutral'){return `<span class="badge badge-${tone}">${esc(text)}</span>`}
function field(path,label,value,unit='',opts={}){const min=opts.min!=null?`min="${opts.min}"`:'';const max=opts.max!=null?`max="${opts.max}"`:'';const step=opts.step??.1;return `<label class="field"><span class="field-label">${label}</span><div class="input-unit"><input type="number" data-project-path="${path}" value="${Number.isFinite(Number(value))?value:''}" step="${step}" ${min} ${max}><span>${unit}</span></div>${opts.hint?`<small>${opts.hint}</small>`:''}</label>`}
function textField(path,label,value){return `<label class="field"><span class="field-label">${label}</span><input type="text" data-project-path="${path}" value="${esc(value)}"></label>`}
function selectField(path,label,value,options,rerender=false){return `<label class="field"><span class="field-label">${label}</span><select data-project-path="${path}" ${rerender?'data-rerender="1"':''}>${options.map(o=>`<option value="${esc(o[0])}" ${String(o[0])===String(value)?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`}
function toggle(path,label,checked,hint=''){return `<label class="toggle"><input type="checkbox" data-project-path="${path}" ${checked?'checked':''}><span class="toggle-track"><span></span></span><span><b>${label}</b>${hint?`<small>${hint}</small>`:''}</span></label>`}
function sectionTitle(eyebrow,title,desc='',actions=''){return `<div class="section-title"><div><div class="eyebrow">${eyebrow||''}</div><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}</div>${actions?`<div class="section-actions">${actions}</div>`:''}</div>`}

function selectorPage(){const p=state.project,c=state.calc||calculateProject(p),dirty=state.calcStamp!==p.updatedAt;return `<main class="page-shell selector-page"><div class="hero selector-hero"><div class="hero-copy"><span class="eyebrow">BLOWER ENGINEERING SELECTOR</span><h1>계산식이 보이는<br><em>산업용 블로워 선정</em></h1><p>풍량·풍압부터 타공 개구부, 에어나이프, 주/가지 배관망, 진공 조건까지 계산하고 실제 카탈로그 데이터와 국내 구매처를 연결합니다.</p><div class="hero-actions">${btn('새 계산 시작','scroll-inputs')}${btn('현재 조건 공유','share','secondary')}</div><div class="trust-row"><span>✓ 계산식/대입값 공개</span><span>✓ P-Q 미검증 자동 표시</span><span>✓ 국내 공급처 연결</span><span>✓ PDF·PNG·HTML 보고서</span></div></div><div class="hero-panel"><div class="hero-panel-head"><span>현재 데이터</span>${badge('LOCAL · OFFLINE READY','good')}</div><div class="hero-panel-grid"><div><strong>${DATA.manufacturers.length}</strong><span>제조사/브랜드</span></div><div><strong>${DATA.variants.length}</strong><span>사양 Variant</span></div><div><strong>${DATA.suppliers.length}</strong><span>한국 공급채널</span></div><div><strong>${DATA.variants.filter(v=>v.max_airflow_m3_min!=null&&(v.discharge_pressure_kpa!=null||v.vacuum_kpa!=null)).length}</strong><span>풍량·압력 데이터</span></div></div><div class="mini-flow"><span>입력</span><i>→</i><span>유체/배관 계산</span><i>→</i><span>Duty</span><i>→</i><span>모델 후보</span><i>→</i><span>구매/RFQ</span></div></div></div>
<section id="selector-inputs" class="selector-workspace"><div class="workspace-head"><div><span class="eyebrow">SELECTION WORKSPACE</span><h2>어떤 기준에서 시작할까요?</h2><p>알고 있는 데이터가 다르므로 계산 시작점을 7개로 분리했습니다.</p></div><span id="dirty-badge">${dirty?badge('입력 변경됨 · 다시 계산 필요','warn'):''}</span></div>${projectBasics()}${selectionTabs()}${inputPanel()}</section>
<section id="selection-results" class="results-anchor ${dirty?'stale':''}">${dirty?`<div class="stale-banner"><b>입력값이 변경되었습니다.</b><span>아래 결과는 직전 계산값입니다. ‘계산하고 블로워 선정’을 눌러 갱신하세요.</span></div>`:''}${resultsHtml(c)}</section></main>`}

function projectBasics(){const p=state.project,e=p.environment;return `<section class="card project-basics"><div class="compact-grid">${textField('projectName','프로젝트명',p.projectName)}${selectField('environment.frequencyHz','전원 주파수',e.frequencyHz,[[60,'60 Hz (한국 표준)'],[50,'50 Hz']])}${selectField('environment.voltageV','기준 전압',e.voltageV,[[380,'380 V'],[220,'220 V'],[440,'440 V']])}</div><details class="advanced-panel"><summary>환경조건 · 설계 여유율 <span>고도/온도/습도에 따른 공기 밀도를 반영합니다.</span></summary><div class="form-grid five">${field('environment.temperatureC','온도',e.temperatureC,'°C',{step:1})}${field('environment.altitudeM','고도',e.altitudeM,'m',{step:10})}${field('environment.relativeHumidityPct','상대습도',e.relativeHumidityPct,'%',{min:0,max:100,step:5})}${field('environment.flowMarginPct','유량 여유율',e.flowMarginPct,'%',{min:0,max:100})}${field('environment.pressureMarginPct','압력 여유율',e.pressureMarginPct,'%',{min:0,max:100})}</div></details></section>`}
const TABDEF=[['flow','Q','풍량 기준','요구 풍량을 알고 있을 때'],['pressure','P','풍압 기준','필요 차압이 핵심일 때'],['openings','○','개구부 기준','타공·사각·장홀 개수'],['airknife','▱','에어나이프','슬롯 폭·간극·속도'],['duct','⑂','배관망','주관+가지관 상세'],['vacuum','▽','진공/흡입','진공도·누설·리프팅'],['application','◇','용도별 빠른선정','공정 목적에서 시작']]
function selectionTabs(){return `<div class="selection-tabs" role="tablist" aria-label="블로워 선정 기준">${TABDEF.map(t=>`<button role="tab" aria-selected="${state.project.tab===t[0]?'true':'false'}" tabindex="${state.project.tab===t[0]?'0':'-1'}" data-tab="${t[0]}" class="${state.project.tab===t[0]?'active':''}"><span class="tab-icon">${t[1]}</span><span><b>${t[2]}</b><small>${t[3]}</small></span></button>`).join('')}</div>`}
function pipeFields(sec){const v=state.project[sec];return `<div class="advanced-block"><div class="advanced-block-title"><b>주배관 / 손실</b><span>필요할 때만 수정하세요.</span></div><div class="form-grid four">${field(`${sec}.mainLengthM`,'주배관 총 길이',v.mainLengthM,'m',{min:0})}${field(`${sec}.mainTargetVelocityMs`,'주배관 목표 유속',v.mainTargetVelocityMs,'m/s',{min:1})}${field(`${sec}.mainElbows`,'90° 엘보',v.mainElbows,'EA',{min:0,step:1})}${field(`${sec}.mainTees`,'T 분기',v.mainTees,'EA',{min:0,step:1})}${field(`${sec}.filterLossKpa`,'필터/소음기 손실',v.filterLossKpa,'kPa',{min:0})}${field(`${sec}.roughnessMm`,'배관 조도',v.roughnessMm,'mm',{min:0,step:.01,hint:'일반 강관 예비값 0.15 mm'})}${field(`${sec}.otherLocalK`,'기타 국부손실 K',v.otherLocalK,'K',{min:0})}</div></div>`}
function branchFields(sec,overrideCountPath=null){const v=state.project[sec],countPath=overrideCountPath||`${sec}.branchCount`,count=overrideCountPath?getPath(state.project,overrideCountPath):v.branchCount;return `<div class="advanced-block"><div class="advanced-block-title"><b>가지관</b><span>기본값으로 계산 후 필요한 경우 조정하세요.</span></div><div class="form-grid four">${overrideCountPath?'':field(countPath,'가지관 수',count,'EA',{min:1,step:1})}${field(`${sec}.branchLengthM`,'가지관 최장 길이',v.branchLengthM,'m',{min:0})}${field(`${sec}.branchTargetVelocityMs`,'가지관 목표 유속',v.branchTargetVelocityMs,'m/s',{min:1})}${field(`${sec}.branchElbows`,'가지관 엘보',v.branchElbows,'EA/branch',{min:0,step:1})}</div></div>`}
function advancedNetwork(sec,overrideCountPath=null,extra=''){return `<details class="advanced-panel engineering-advanced"><summary>상세 배관 · 손실 설정 <span>기본값이 입력되어 있어 바로 계산할 수 있습니다.</span></summary>${extra}${branchFields(sec,overrideCountPath)}${pipeFields(sec)}</details>`}
function calcRow(){return `<div class="calculate-row">${btn('계산하고 블로워 선정','calculate')}<p><b>빠른 사용:</b> 필수값만 바꾼 뒤 계산해도 됩니다. 상세 배관·환경값은 필요할 때 펼쳐 수정하세요.</p></div>`}
function inputHeader(title,desc){return `<div class="input-header"><div><span>QUICK ENGINEERING INPUT</span><h3>${title}</h3><p>${desc}</p></div><div class="precision-badge"><b>간결 입력</b><span>필수값 우선 · 상세값은 접어서 관리</span></div></div>`}
function quickHint(text='파란 영역의 필수값만 확인하고 바로 계산할 수 있습니다.'){return `<div class="quick-hint"><span>QUICK</span><p>${text}</p></div>`}
function inputPanel(){const t=state.project.tab,p=state.project;
if(t==='flow'){const v=p.flow;return `<section class="card">${inputHeader('풍량 기준 선정','요구 풍량과 말단 정압만 알면 시작할 수 있습니다.')} ${quickHint()}<div class="form-grid essential-grid">${field('flow.requiredFlowM3Min','요구 풍량',v.requiredFlowM3Min,'m³/min',{min:0})}${field('flow.terminalPressureKpa','말단 요구 정압',v.terminalPressureKpa,'kPa',{min:0})}</div>${advancedNetwork('flow')}${calcRow()}</section>`}
if(t==='pressure'){const v=p.pressure;return `<section class="card">${inputHeader('풍압 기준 선정','필요 풍압과 최소 풍량만 입력하면 배관손실을 합산합니다.')} ${quickHint()}<div class="form-grid essential-grid">${field('pressure.requiredPressureKpa','요구 풍압',v.requiredPressureKpa,'kPa',{min:0})}${field('pressure.minimumFlowM3Min','최소 필요 풍량',v.minimumFlowM3Min,'m³/min',{min:0})}</div>${advancedNetwork('pressure')}${calcRow()}</section>`}
if(t==='openings'){const v=p.openings;let dims=v.shape==='circle'?field('openings.diameterMm','직경',v.diameterMm,'mm',{min:0}):v.shape==='rectangle'?field('openings.widthMm','폭',v.widthMm,'mm',{min:0})+field('openings.heightMm','높이',v.heightMm,'mm',{min:0}):v.shape==='slot'?field('openings.lengthMm','슬롯 길이',v.lengthMm,'mm',{min:0})+field('openings.heightMm','슬롯 간극',v.heightMm,'mm',{min:.1}):field('openings.widthMm','장홀 폭',v.widthMm,'mm',{min:0})+field('openings.lengthMm','전체 길이',v.lengthMm,'mm',{min:0});const extra=`<div class="advanced-block"><div class="advanced-block-title"><b>개구부 보정</b><span>형상을 잘 모르면 기본 Cd를 유지하세요.</span></div><div class="form-grid essential-grid">${field('openings.dischargeCoefficient','유량계수 Cd',v.dischargeCoefficient,'',{min:.2,max:1,step:.01,hint:'형상 미확인 시 0.80~0.90 예비값'})}</div></div>`;return `<section class="card">${inputHeader('개구부·타공 기준 선정','형상, 규격, 개수, 목표 출구속도만 입력하면 총 요구풍량을 계산합니다.')} ${quickHint('개구부 형상·크기·개수와 목표 속도만 먼저 입력하세요.')}<div class="form-grid essential-grid">${selectField('openings.shape','개구부 형상',v.shape,[['circle','원형 타공'],['rectangle','사각 개구부'],['slot','직사각 슬롯'],['oblong','장홀(Oblong)']],true)}${dims}${field('openings.count','개구부 개수',v.count,'EA',{min:1,step:1})}${field('openings.targetExitVelocityMs','목표 출구속도',v.targetExitVelocityMs,'m/s',{min:1})}</div>${advancedNetwork('openings',null,extra)}${calcRow()}</section>`}
if(t==='airknife'){const v=p.airknife;const extra=`<div class="advanced-block"><div class="advanced-block-title"><b>공정 보정 / 기록</b><span>액절단 성능 검토에 필요한 추가 조건입니다.</span></div><div class="form-grid four">${field('airknife.dischargeCoefficient','슬롯 Cd',v.dischargeCoefficient,'',{min:.2,max:1,step:.01})}${field('airknife.lineSpeedMMin','라인 속도',v.lineSpeedMMin,'m/min',{min:0})}${field('airknife.blowZoneLengthMm','유효 블로우 존',v.blowZoneLengthMm,'mm',{min:0})}${field('airknife.standoffMm','노즐 이격거리',v.standoffMm??20,'mm',{min:0})}${field('airknife.angleDeg','분사각',v.angleDeg??30,'°',{min:0,max:90,step:1})}</div><div class="callout info compact-callout"><b>R2R 도금 팁</b><span>노즐은 원 탱크 쪽으로 액을 되돌리는 방향을 우선 검토합니다. 이격거리·분사각·액 물성·스트립 표면은 현장 검증 항목입니다.</span></div></div>`;return `<section class="card">${inputHeader('에어나이프·액절단 선정','폭, 슬롯 간극, 개수, 목표 제트속도 4개 값으로 빠르게 시작합니다.')} ${quickHint('에어나이프의 폭·간극·개수·목표 제트속도만 먼저 입력하세요.')}<div class="form-grid essential-grid">${field('airknife.knifeWidthMm','에어나이프 유효 폭',v.knifeWidthMm,'mm',{min:1})}${field('airknife.slotGapMm','슬롯 간극',v.slotGapMm,'mm',{min:.1,step:.1})}${field('airknife.knifeCount','에어나이프 수',v.knifeCount,'EA',{min:1,step:1})}${field('airknife.targetExitVelocityMs','목표 제트속도',v.targetExitVelocityMs,'m/s',{min:1})}</div>${advancedNetwork('airknife','airknife.knifeCount',extra)}${calcRow()}</section>`}
if(t==='duct'){const v=p.duct;return `<section class="card">${inputHeader('배관망·가지관 상세 설계','이 탭은 배관망을 직접 설계할 때 사용합니다. 각 가지관의 유량·길이·말단압력을 개별 입력합니다.')}<div class="branch-editor"><div class="branch-head"><b>가지관 구성</b>${btn('+ 가지관 추가','add-branch','secondary')}</div>${v.branches.map((b,i)=>`<div class="branch-row"><div class="branch-row-title"><input type="text" data-project-path="duct.branches.${i}.name" value="${esc(b.name)}"><button data-action="remove-branch" data-index="${i}" ${v.branches.length<=1?'disabled':''}>×</button></div><div class="form-grid four">${field(`duct.branches.${i}.outletCount`,'말단 수량',b.outletCount,'EA',{min:1,step:1})}${field(`duct.branches.${i}.flowEachM3Min`,'말단당 풍량',b.flowEachM3Min,'m³/min',{min:0})}${field(`duct.branches.${i}.lengthM`,'가지 길이',b.lengthM,'m',{min:0})}${field(`duct.branches.${i}.terminalPressureKpa`,'말단 요구압',b.terminalPressureKpa,'kPa',{min:0})}${field(`duct.branches.${i}.targetVelocityMs`,'목표 유속',b.targetVelocityMs,'m/s',{min:1})}${field(`duct.branches.${i}.elbows`,'엘보',b.elbows,'EA',{min:0,step:1})}${field(`duct.branches.${i}.tees`,'T 피팅',b.tees,'EA',{min:0,step:1})}${field(`duct.branches.${i}.otherK`,'기타 K',b.otherK,'K',{min:0})}</div></div>`).join('')}</div><details class="advanced-panel" open><summary>주배관 / 공통 손실 <span>배관망 탭에서는 상세값을 기본 표시합니다.</span></summary>${pipeFields('duct')}</details>${calcRow()}</section>`}
if(t==='vacuum'){const v=p.vacuum;const extra=`<div class="advanced-block"><div class="advanced-block-title"><b>누설 / 리프팅 보정</b><span>흡착 계산이 필요하지 않으면 기본값을 유지하세요.</span></div><div class="form-grid four">${field('vacuum.leakageReservePct','누설 여유',v.leakageReservePct,'%',{min:0})}${field('vacuum.cupAreaCm2','흡착면적',v.cupAreaCm2,'cm²',{min:0})}${field('vacuum.loadKg','리프팅 하중',v.loadKg,'kg',{min:0})}${field('vacuum.holdingSafetyFactor','흡착 안전율',v.holdingSafetyFactor,'',{min:1,step:.1})}</div></div>`;return `<section class="card">${inputHeader('진공·흡입 기준 선정','목표 진공도와 기본 흡입풍량만 입력해 후보를 먼저 찾을 수 있습니다.')} ${quickHint()}<div class="form-grid essential-grid">${field('vacuum.targetVacuumKpa','목표 진공도',v.targetVacuumKpa,'kPa',{min:0})}${field('vacuum.suctionFlowM3Min','기본 흡입풍량',v.suctionFlowM3Min,'m³/min',{min:0})}</div>${advancedNetwork('vacuum',null,extra)}${calcRow()}</section>`}
const v=p.application;const extra=`<div class="advanced-block"><div class="advanced-block-title"><b>운전 선호조건</b></div><div class="toggle-grid">${toggle('application.continuousDuty','연속 운전',v.continuousDuty,'베어링·온도·정비성 검토 강화')}${toggle('application.preferOilFree','오일프리 선호',v.preferOilFree,'청정 공정 후보 우선')}</div></div>`;return `<section class="card">${inputHeader('용도별 빠른 선정','용도와 최소 풍량·풍압만 넣고 후보를 빠르게 찾습니다.')} ${quickHint()}<div class="form-grid essential-grid">${selectField('application.application','사용처',v.application,[['plating','도금 / 표면처리'],['wash_drying','세척 후 건조'],['film_web','필름 / 웹 공정'],['wastewater','폐수처리 폭기'],['pneumatic_conveying','공압 이송'],['aquaculture','양식장 폭기']],true)}${field('application.requiredFlowM3Min','요구 풍량',v.requiredFlowM3Min,'m³/min',{min:0})}${field('application.requiredPressureKpa','요구 풍압',v.requiredPressureKpa,'kPa',{min:0})}</div>${advancedNetwork('application',null,extra)}${calcRow()}</section>`}

function reportOpts(){return {...REPORT_DEFAULTS,...(state.project.reportOptions||{})}}
function resultToolbar(){const o=reportOpts(),extra=Object.entries(o).filter(([k,v])=>v&&!['candidate','pipeSchedule','warnings'].includes(k)).length;return `<nav class="result-toolbar" aria-label="계산 결과 바로가기"><div class="result-toolbar-main"><b>결과 메뉴</b><button data-action="scroll-results">요약</button><button data-action="scroll-candidates">선정 후보</button><button data-action="scroll-pipes">배관표</button><button data-action="scroll-formulas">계산식</button><button data-action="scroll-report">보고서 미리보기</button></div><div class="result-toolbar-actions"><button class="btn btn-secondary" data-action="report-settings">보고서 구성${extra?` +${extra}`:''}</button><button class="btn btn-primary" data-action="export-pdf">PDF 저장</button></div></nav>`}
function resultsHtml(c){const p=state.project,cands=buildCandidates(DATA,c,p),passing=cands.filter(x=>x.endpointPass),vis=(passing.length?passing:cands).slice(0,12),sel=cands.find(x=>x.variant.id===p.selectedVariantId)||vis[0]||null;return `<div class="results-stack">${resultToolbar()}<section id="result-summary" class="card result-overview">${sectionTitle('CALCULATION RESULT','설계 Duty와 배관 권장값','입력 조건에 설계 여유율과 배관 손실을 반영한 1차 엔지니어링 결과.')}<div class="metrics-grid">${metric('설계 풍량',f(c.designFlowM3Min,3),'m³/min',`원계산 ${f(c.rawFlowM3Min,3)}`)}${metric(p.tab==='vacuum'?'설계 진공도':'설계 풍압',f(c.designPressureKpa,3),'kPa','손실+여유 반영')}${metric('주배관 권장',`Ø${c.selectedMainStandardDiameterMm}`,'mm',`계산 ${f(c.recommendedMainDiameterMm,1)} mm`)}${metric('주배관 실제 유속',f(c.mainActualVelocityMs,2),'m/s',`손실 ${f(c.mainFrictionLossKpa+c.mainLocalLossKpa,3)} kPa`)}${metric('공기동력',f(c.estimatedAirPowerKw,2),'kW','Q × ΔP')}${metric('모터 예비 추정',f(c.estimatedMotorPowerKw,2),'kW','η=0.58 + 10%')}</div><div class="type-strip"><span>우선 검토 방식</span>${c.recommendedTypes.map(x=>badge(x,'info')).join('')}</div>${c.warnings.length?`<div class="warning-list">${c.warnings.map(x=>`<div>⚠ ${esc(x)}</div>`).join('')}</div>`:''}${formulaHtml(c)}</section>${branchTable(c)}${candidateSection(vis,passing,sel)}${reportSheet(c,sel)}<section class="card export-card">${sectionTitle('REPORT','보고서 저장','상단의 ‘결과 / 저장’ 메뉴에서도 언제든 저장할 수 있습니다.',btn('보고서 구성','report-settings','secondary'))}<div class="export-actions">${btn('브라우저에 저장','save-report')}${btn('PDF 저장','export-pdf','secondary')}${btn('PNG 이미지','export-png','secondary')}${btn('HTML 문서','export-html','secondary')}${btn('JSON 데이터','export-json','ghost')}${btn('인쇄','print','ghost')}</div><p class="table-note">기본 보고서는 요약·선정후보·배관표·최종 주의사항으로 간결하게 구성됩니다. 계산식/환경조건/출처/구매처는 ‘보고서 구성’에서 체크해 추가합니다.</p></section></div>`}
function metric(l,v,u,s){return `<div class="metric"><span>${l}</span><strong>${v}<em> ${u}</em></strong><small>${s}</small></div>`}
function formulaHtml(c){return `<details id="result-formulas" class="formula-box"><summary><span><b>계산 과정</b><small>공식·대입값·결과 상세 보기</small></span><strong>펼치기</strong></summary><ol>${c.formulas.map(x=>`<li><div><strong>${esc(x.label)}</strong><code>${esc(x.formula)}</code></div><p>${esc(x.substitution)}</p><b>→ ${esc(x.result)}</b>${x.note?`<small>${esc(x.note)}</small>`:''}</li>`).join('')}</ol><div class="formula-env">공기밀도 ρ=${c.airDensityKgM3.toFixed(4)} kg/m³ · 동점성 계산용 μ=${c.dynamicViscosityPaS.toExponential(3)} Pa·s</div></details>`}
function branchTable(c){return `<section id="result-pipes" class="card">${sectionTitle('PIPE / BRANCH SCHEDULE','배관 및 가지관 사이징','표준 내경은 목표 유속을 만족하도록 계산 내경 이상에서 선택합니다.')}<div class="table-wrap"><table class="data-table"><thead><tr><th>구간</th><th>원 풍량</th><th>계산 내경</th><th>표준 권장</th><th>실제 유속</th><th>마찰손실</th><th>국부손실</th><th>말단+경로</th></tr></thead><tbody><tr class="main-row"><td><b>주배관</b></td><td>${f(c.designFlowM3Min,3)}</td><td>${f(c.recommendedMainDiameterMm,1)} mm</td><td><b>Ø${c.selectedMainStandardDiameterMm} mm</b></td><td>${f(c.mainActualVelocityMs,2)} m/s</td><td>${f(c.mainFrictionLossKpa,3)} kPa</td><td>${f(c.mainLocalLossKpa,3)} kPa</td><td>${f(c.rawPressureKpa,3)} kPa</td></tr>${c.branchResults.map(b=>`<tr><td>${esc(b.name)}</td><td>${f(b.flowM3Min,3)}</td><td>${f(b.recommendedDiameterMm,1)} mm</td><td><b>Ø${b.selectedStandardDiameterMm} mm</b></td><td>${f(b.actualVelocityMs,2)} m/s</td><td>${f(b.frictionLossKpa,3)} kPa</td><td>${f(b.localLossKpa,3)} kPa</td><td>${f(b.pathPressureKpa,3)} kPa</td></tr>`).join('')}</tbody></table></div><p class="table-note">※ 실제 KS/JIS/Sch 배관의 내경과 블로워 토출 플랜지 규격을 대조하고 Reducer/Expander 손실을 추가 확인해야 합니다.</p></section>`}
function candidateSection(vis,passing,sel){return `<section id="result-candidates" class="card">${sectionTitle('MODEL MATCHING',`블로워 후보 ${passing.length}개`,passing.length?'최대풍량·최대압력 endpoint가 설계 Duty 이상인 1차 후보입니다. 최종 발주 전 공식 P-Q 운전점 검증이 필요합니다.':'현재 DB에서 endpoint를 동시에 만족하는 모델이 없습니다. 아래는 근접 후보입니다.')}<div class="candidate-list">${vis.map((x,i)=>candidateCard(x,i+1,sel?.variant.id===x.variant.id)).join('')}</div></section>`}
function candidateCard(c,i,selected){const pressure=c.variant.discharge_pressure_kpa??c.variant.vacuum_kpa,tone=c.curveStatus==='verified'?'good':c.endpointPass?'warn':'neutral';return `<article class="candidate ${selected?'selected':''}"><div class="candidate-rank">${i}</div><div class="candidate-main"><div class="candidate-title"><span>${esc(c.manufacturer.name)}</span><h4>${esc(c.model.model_name)}</h4><small>${esc(c.model.series||'')} · ${esc(c.model.blower_type_raw||'')}</small></div><div class="candidate-specs"><span><b>${f(c.variant.motor_kw)}</b> kW</span><span><b>${f(c.variant.max_airflow_m3_min)}</b> m³/min</span><span><b>${f(pressure)}</b> kPa</span><span><b>${f(c.variant.frequency_hz,0)}</b> Hz</span></div></div><div class="candidate-status">${badge(c.curveStatus==='verified'?'P-Q 검증됨':c.endpointPass?'P-Q 검증 필요':c.curveStatus==='missing_data'?'데이터 부족':'endpoint 부족',tone)}<span class="score">후보점수 <b>${c.score}</b></span></div><div class="candidate-actions"><button class="btn btn-${selected?'primary':'secondary'}" data-action="select-candidate" data-id="${c.variant.id}">${selected?'선택됨':'이 모델 선택'}</button><button class="btn btn-ghost" data-action="candidate-detail" data-id="${c.variant.id}">상세</button></div></article>`}
function reportInputSummary(c){const p=state.project;return `<div class="report-info-grid"><div><span>선정 기준</span><b>${esc(TABDEF.find(x=>x[0]===p.tab)?.[2]||p.tab)}</b></div><div><span>원 계산 풍량</span><b>${c.rawFlowM3Min.toFixed(3)} m³/min</b></div><div><span>원 요구압력</span><b>${c.rawPressureKpa.toFixed(3)} kPa</b></div><div><span>전원</span><b>${p.environment.frequencyHz} Hz / ${p.environment.voltageV} V</b></div></div>`}
function reportEnvironment(c){const e=state.project.environment;return `<div class="report-info-grid"><div><span>온도</span><b>${f(e.temperatureC,1)} °C</b></div><div><span>고도</span><b>${f(e.altitudeM,0)} m</b></div><div><span>상대습도</span><b>${f(e.relativeHumidityPct,0)} %</b></div><div><span>공기밀도</span><b>${c.airDensityKgM3.toFixed(4)} kg/m³</b></div><div><span>유량 여유율</span><b>${f(e.flowMarginPct,1)} %</b></div><div><span>압력 여유율</span><b>${f(e.pressureMarginPct,1)} %</b></div></div>`}
function reportSources(sel,includeSuppliers){if(!sel)return '';const suppliers=includeSuppliers&&sel.suppliers?.length?`<div class="report-supplier-list">${sel.suppliers.slice(0,5).map(s=>`<div><b>${esc(s.name)}</b><span>${esc(s.region||'한국')} · ${esc(s.phone||s.email||'공식 문의채널')}</span></div>`).join('')}</div>`:'';return `<div class="report-source-box"><p><b>모델 데이터 출처</b> ${esc(sel.model.source_document||sel.variant.source_page_or_section||'등록 데이터')}</p><p><b>검증 상태</b> ${sel.curveStatus==='verified'?'P-Q 검증됨':'공식 P-Q 운전점 확인 필요'}</p>${suppliers}</div>`}
function reportSheet(c,sel){const o=reportOpts();const candidate=o.candidate&&sel?`<div class="report-selected"><span>선정 후보</span><h3>${esc(sel.manufacturer.name)} · ${esc(sel.model.model_name)}</h3><p>${f(sel.variant.motor_kw)} kW · ${f(sel.variant.max_airflow_m3_min)} m³/min · ${f(sel.variant.discharge_pressure_kpa??sel.variant.vacuum_kpa)} kPa · ${sel.variant.frequency_hz??'—'} Hz</p><b>${sel.curveStatus==='verified'?'P-Q 검증됨':'최종 발주 전 P-Q 운전점 확인 필요'}</b></div>`:'';const pipe=o.pipeSchedule?`<h3>배관 Schedule</h3><div class="report-table-wrap"><table><thead><tr><th>구간</th><th>풍량</th><th>권장관경</th><th>유속</th><th>경로압력</th></tr></thead><tbody><tr><td>주배관</td><td>${c.designFlowM3Min.toFixed(3)}</td><td>Ø${c.selectedMainStandardDiameterMm}</td><td>${c.mainActualVelocityMs.toFixed(2)}</td><td>${c.rawPressureKpa.toFixed(3)}</td></tr>${c.branchResults.slice(0,10).map(b=>`<tr><td>${esc(b.name)}</td><td>${b.flowM3Min.toFixed(3)}</td><td>Ø${b.selectedStandardDiameterMm}</td><td>${b.actualVelocityMs.toFixed(2)}</td><td>${b.pathPressureKpa.toFixed(3)}</td></tr>`).join('')}</tbody></table></div>`:'';const formulas=o.formulas?`<h3>계산식 상세</h3><div class="report-formula-cards">${c.formulas.map((x,i)=>`<article><span>${i+1}</span><div><b>${esc(x.label)}</b><code>${esc(x.formula)}</code><p>${esc(x.substitution)}</p><strong>→ ${esc(x.result)}</strong>${x.note?`<small>${esc(x.note)}</small>`:''}</div></article>`).join('')}</div>`:'';const warnings=o.warnings?`<div class="report-warning-box"><b>최종 발주 전 확인</b><p>최대풍량과 최대풍압은 같은 운전점이 아닙니다. 실제 배관·필터·노즐 조건과 제조사 공식 P-Q 곡선에서 Duty point를 확인하세요.</p>${c.warnings.length?`<ul>${c.warnings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div>`:'';return `<section id="report-sheet" class="report-sheet"><div class="report-head"><div><span class="report-logo">BF</span><div><b>BlowerFit KR</b><small>Engineering Selection Report</small></div></div><span>${new Date().toLocaleDateString('ko-KR')}</span></div><div class="report-title-row"><div><h2>${esc(state.project.projectName)}</h2><p class="report-sub">산업용 블로워 예비 선정 및 배관 사이징 리포트</p></div><button class="report-config-btn" data-action="report-settings">보고서 구성 ⚙</button></div><div class="report-kpis"><div><span>설계 풍량</span><b>${c.designFlowM3Min.toFixed(3)} m³/min</b></div><div><span>${state.project.tab==='vacuum'?'설계 진공도':'설계 풍압'}</span><b>${c.designPressureKpa.toFixed(3)} kPa</b></div><div><span>주배관</span><b>Ø${c.selectedMainStandardDiameterMm} mm</b></div><div><span>예비 모터</span><b>${c.estimatedMotorPowerKw.toFixed(2)} kW</b></div></div>${o.inputSummary?`<h3>입력 / 설계 기준</h3>${reportInputSummary(c)}`:''}${o.environment?`<h3>환경조건 / 여유율</h3>${reportEnvironment(c)}`:''}${candidate}${pipe}${formulas}${(o.sources||o.suppliers)?`<h3>출처 / 구매 연결</h3>${reportSources(sel,o.suppliers)}`:''}${warnings}<div class="report-foot"><b>Engineering note</b><p>본 결과는 예비 선정용입니다. 최종 발주 전 실제 배관/피팅, 모터 전원, 운전시간, 흡입필터, 소음, 유체 성상 및 제조사 공식 P-Q 곡선을 확인해야 합니다.</p></div></section>`}

function productsPage(){const rows=productRows(DATA,state.productFilters),types=[...new Set(DATA.models.map(m=>m.blower_type_raw).filter(Boolean))].sort(),mfr=DATA.manufacturers.slice().sort((a,b)=>a.name.localeCompare(b.name));return `<main class="page-shell"><div class="hero compact"><div><span class="eyebrow">CATALOG DATABASE</span><h1>블로워 제품 데이터베이스</h1><p>제조사·형식·출력·풍량·풍압·주파수로 초기 사양 데이터셋을 검색합니다.</p></div><div class="hero-stat"><strong>${DATA.variants.length}</strong><span>사양 variant</span><strong>${DATA.manufacturers.length}</strong><span>제조사/브랜드</span></div></div><section class="card">${sectionTitle('SEARCH','검색 및 필터','한글·영문 제조사명, 모델명, 용도 태그 검색',state.compareIds.length>1?btn(`선택 ${state.compareIds.length}개 비교`,'open-compare'):'')}<div class="searchbar"><span>⌕</span><input id="product-q" data-product-filter="q" value="${esc(state.productFilters.q)}" placeholder="예: HRB-1202, BESLA, ring blower, plating..."></div><div class="filter-grid"><label class="field"><span class="field-label">블로워 형식</span><select data-product-filter="type"><option value="">전체 형식</option>${types.map(x=>`<option value="${esc(x)}" ${state.productFilters.type===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label class="field"><span class="field-label">제조사</span><select data-product-filter="manufacturer"><option value="">전체 제조사</option>${mfr.map(x=>`<option value="${x.id}" ${state.productFilters.manufacturer===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label class="field"><span class="field-label">주파수</span><select data-product-filter="frequency"><option value="60" ${String(state.productFilters.frequency)==='60'?'selected':''}>60 Hz</option><option value="50" ${String(state.productFilters.frequency)==='50'?'selected':''}>50 Hz</option><option value="all" ${state.productFilters.frequency==='all'?'selected':''}>전체</option></select></label>${productNum('minKw','최소 kW','kW')}${productNum('maxKw','최대 kW','kW')}${productNum('minFlow','최소 풍량','m³/min')}${productNum('minPressure','최소 풍압','kPa')}<label class="toggle"><input type="checkbox" data-product-filter="koreaOnly" ${state.productFilters.koreaOnly?'checked':''}><span class="toggle-track"><span></span></span><span><b>한국 구매경로 우선</b></span></label></div></section><section class="card">${sectionTitle('RESULTS',`검색 결과 ${rows.length}건`,'최대풍량과 최대풍압은 서로 다른 endpoint일 수 있으므로 실제 P-Q 검증이 필요합니다.')}<div id="product-results">${productTable(rows)}</div></section></main>`}
function productNum(k,l,u){return `<label class="field"><span class="field-label">${l}</span><div class="input-unit"><input type="number" data-product-filter="${k}" value="${state.productFilters[k]}" min="0" step="0.1"><span>${u}</span></div></label>`}
function productTable(rows){if(!rows.length)return `<div class="empty-state"><div class="empty-icon">◎</div><h3>검색 결과가 없습니다</h3><p>필터 범위를 넓히거나 한국 구매경로 우선을 해제해보세요.</p></div>`;return `<div class="table-wrap product-table-wrap"><table class="data-table product-table"><thead><tr><th>비교</th><th>제조사 / 모델</th><th>형식</th><th>kW</th><th>HP</th><th>풍량</th><th>풍압</th><th>진공</th><th>Hz</th><th>상태</th><th>★</th></tr></thead><tbody>${rows.map(r=>`<tr><td><input type="checkbox" data-action="compare-toggle" data-id="${r.variant.id}" ${state.compareIds.includes(r.variant.id)?'checked':''} ${!state.compareIds.includes(r.variant.id)&&state.compareIds.length>=4?'disabled':''}></td><td><b>${esc(r.model.model_name)}</b><small>${esc(r.manufacturer.name)}<br>${esc(r.model.series||'')}</small></td><td>${esc(r.model.blower_type_raw||'')}</td><td>${f(r.variant.motor_kw)}</td><td>${f(r.variant.motor_hp)}</td><td>${f(r.variant.max_airflow_m3_min,3)}<small>m³/min</small></td><td>${f(r.variant.discharge_pressure_kpa)}<small>kPa</small></td><td>${f(r.variant.vacuum_kpa)}<small>kPa</small></td><td>${f(r.variant.frequency_hz,0)}</td><td>${badge(r.variant.needs_curve_verification?'P-Q 확인':'검증값',r.variant.needs_curve_verification?'warn':'good')}</td><td><button class="star-btn ${state.favorites.includes(r.variant.id)?'on':''}" data-action="favorite" data-id="${r.variant.id}">★</button></td></tr>`).join('')}</tbody></table></div>`}
function compareModal(){const rows=productRows(DATA,state.productFilters).filter(r=>state.compareIds.includes(r.variant.id));return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>모델 비교</h3><button class="icon-btn" data-action="close-compare">×</button></div><div class="modal-body"><div class="table-wrap"><table class="compare-table"><thead><tr><th>항목</th>${rows.map(r=>`<th>${esc(r.model.model_name)}</th>`).join('')}</tr></thead><tbody>${[['제조사',r=>r.manufacturer.name],['형식',r=>r.model.blower_type_raw||'—'],['모터',r=>`${f(r.variant.motor_kw)} kW / ${f(r.variant.motor_hp)} HP`],['풍량',r=>`${f(r.variant.max_airflow_m3_min,3)} m³/min`],['풍압',r=>`${f(r.variant.discharge_pressure_kpa)} kPa`],['진공',r=>`${f(r.variant.vacuum_kpa)} kPa`],['주파수',r=>`${f(r.variant.frequency_hz,0)} Hz`],['소음',r=>`${f(r.variant.sound_dba)} dB(A)`],['중량',r=>`${f(r.variant.weight_kg)} kg`],['출처',r=>r.model.source_document||'—']].map(([lab,fn])=>`<tr><th>${lab}</th>${rows.map(r=>`<td>${esc(fn(r))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div></div></div>`}

function suppliersPage(){const q=state.supplierQuery.toLowerCase(),rows=DATA.suppliers.filter(s=>[s.name,s.region,s.related_manufacturer_name,s.address].filter(Boolean).join(' ').toLowerCase().includes(q));return `<main class="page-shell"><div class="hero compact"><div><span class="eyebrow">PROCUREMENT</span><h1>한국 구매처·공급사 디렉터리</h1><p>제조사 직판, 공식 한국법인, 공식 문의 채널을 구분합니다. 확인되지 않은 판매처 관계는 임의로 대리점이라 표시하지 않습니다.</p></div><div class="hero-stat"><strong>${DATA.suppliers.length}</strong><span>검증 채널</span><strong>${new Set(DATA.suppliers.map(s=>s.region).filter(Boolean)).size}</strong><span>지역</span></div></div><section class="card">${sectionTitle('SEARCH','공급처 찾기','업체명, 제조사, 지역, 주소로 검색')}<div class="searchbar"><span>⌕</span><input id="supplier-q" data-supplier-filter="q" value="${esc(state.supplierQuery)}" placeholder="예: 인천, Atlas Copco, 황해전기..."></div></section><div id="supplier-results" class="supplier-grid">${supplierCards(rows)}</div></main>`}
function supplierCards(rows){const label={manufacturer_direct:'제조사 직판',official_korea_office:'공식 한국법인',official_korea_manufacturing:'한국 생산/법인',official_contact_form:'공식 문의',manufacturer_direct_profile:'제조사 프로필'};return rows.map(s=>`<section class="card supplier-card"><div class="supplier-top"><div>${badge(label[s.supplier_type]||s.supplier_type,s.supplier_type.includes('official')?'good':'info')}<h3>${esc(s.name)}</h3><p>${esc(s.related_manufacturer_name||'')}</p></div><span class="region-chip">${esc(s.region||'한국')}</span></div><dl><dt>주소</dt><dd>${esc(s.address||'공식 페이지 확인')}</dd><dt>전화</dt><dd>${esc(s.phone||'공식 문의폼')}</dd><dt>이메일</dt><dd>${esc(s.email||'—')}</dd><dt>서비스</dt><dd>${esc((s.services||[]).join(' · '))}</dd><dt>확인일</dt><dd>${esc(s.verified_at||'—')}</dd></dl><div class="supplier-actions">${s.website?`<a class="btn btn-primary" href="${esc(s.website)}" target="_blank" rel="noreferrer">공식 사이트 ↗</a>`:''}${s.email?`<a class="btn btn-secondary" href="mailto:${esc(s.email)}">이메일 문의</a>`:''}${s.phone?`<a class="btn btn-ghost" href="tel:${esc(s.phone.replace(/[^0-9+]/g,''))}">전화</a>`:''}</div></section>`).join('')}

function guidePage(){const checks=['공식 P-Q 곡선의 실제 Duty point','60/50Hz 및 모터 정격전압','흡입온도·고도·습도 보정','필터·소음기·체크밸브 실제 손실','토출 플랜지/배관 내경·재질','모터 전류·인버터 허용 주파수','연속운전 온도·베어링·그리스','가스 부식성·미스트·수분','소음·진동·방음패키지','안전밸브/릴리프 및 과부하 보호','현장 설치공간·점검공간','보증·A/S·예비품·납기'];return `<main class="page-shell"><div class="hero compact"><div><span class="eyebrow">ENGINEERING GUIDE</span><h1>블로워 선정 기술 가이드</h1><p>계산기 내부에서 사용하는 핵심 개념과 최종 발주 전에 반드시 확인해야 할 항목입니다.</p></div></div><div class="guide-grid">${guideCard('1. 최대풍량 ≠ 최대풍압','카탈로그의 최대풍량은 보통 낮은 차압 영역, 최대풍압은 거의 무유량 영역의 endpoint입니다. 두 숫자를 동시에 만족하는 것으로 해석하면 안 됩니다.','Q(P_required) ≥ Q_required')}${guideCard('2. 배관 손실','원형 배관 직관 마찰은 Darcy–Weisbach, 엘보·T 등은 국부손실계수 K로 계산합니다.','ΔP = f(L/D)(ρv²/2) + ΣK(ρv²/2)')}${guideCard('3. 개구부·노즐','개구부 총면적과 목표 출구속도로 풍량을 계산하고 유량계수 Cd로 동압을 예비 산정합니다.','Q=A·v,  ΔP≈ρ/2·(v/Cd)²')}${guideCard('4. 에어나이프','슬롯 폭×간극×개수로 유효 개구면적을 얻습니다. 실제 액절단은 분사각·이격거리·액 물성·스트립 속도에 좌우됩니다.','A = width × gap × count')}${guideCard('5. 공기 밀도 보정','온도·고도·상대습도에 따른 공기 밀도를 동압과 배관손실에 반영합니다.','ρ=Pd/(RdT)+Pv/(RvT)')}${guideCard('6. 블로워 방식','링/사이드채널, 루츠/PD, 터보/원심, 스크류는 효율·유량·차압·유지보수 특성이 다릅니다.','Duty + control + service + TCO')}</div><section class="card">${sectionTitle('FINAL CHECK','최종 발주 체크리스트','웹 계산 결과를 구매 사양서로 확정하기 전에 제조사와 교차 확인하세요.')}<div class="check-grid">${checks.map(x=>`<label><input type="checkbox"> <span>${x}</span></label>`).join('')}</div></section></main>`}
function guideCard(t,p,equ){return `<section class="card"><h2>${t}</h2><p>${p}</p><div class="guide-equation"><code>${equ}</code></div></section>`}

function reportsPage(){return `<main class="page-shell"><div class="hero compact"><div><span class="eyebrow">LOCAL REPORTS</span><h1>저장한 계산 리포트</h1><p>서버 없이 브라우저 LocalStorage에 저장됩니다. JSON 백업으로 다른 환경에 보관할 수 있습니다.</p></div><div class="hero-stat"><strong>${state.reports.length}</strong><span>저장 리포트</span></div></div><section class="card">${sectionTitle('MY REPORTS','내 리포트','최대 50건을 로컬에 보관합니다.',`${state.reports.length?btn('전체 JSON 백업','export-all-reports','secondary'):''}${btn('JSON 백업 불러오기','import-reports','ghost')}`)}${state.reports.length?`<div class="saved-report-list">${state.reports.map(r=>`<article><div>${badge(r.project.tab,'info')}<h3>${esc(r.project.projectName)}</h3><p>${new Date(r.createdAt).toLocaleString('ko-KR')} · ${r.calculation.designFlowM3Min.toFixed(2)} m³/min · ${r.calculation.designPressureKpa.toFixed(2)} kPa</p></div><div><button class="btn btn-secondary" data-action="load-report" data-id="${r.id}">불러오기</button><button class="btn btn-ghost" data-action="delete-report" data-id="${r.id}">삭제</button></div></article>`).join('')}</div>`:`<div class="empty-state"><div class="empty-icon">◎</div><h3>저장한 리포트가 없습니다</h3><p>선정 계산기에서 ‘브라우저에 저장’을 누르면 여기에 보관됩니다.</p></div>`}</section></main>`}

function getPath(o,path){return path.split('.').reduce((a,k)=>a?.[Number.isInteger(Number(k))?Number(k):k],o)}
function setPath(o,path,value){const parts=path.split('.');let cur=o;for(let i=0;i<parts.length-1;i++){const k=/^\d+$/.test(parts[i])?Number(parts[i]):parts[i];cur=cur[k]}const last=/^\d+$/.test(parts.at(-1))?Number(parts.at(-1)):parts.at(-1);cur[last]=value}
function markDirty(){state.project.updatedAt=now();save(storage.project,state.project);const el=$('#dirty-badge');if(el)el.innerHTML=badge('입력 변경됨 · 다시 계산 필요','warn');$('#selection-results')?.classList.add('stale')}
function candidateById(id){const c=buildCandidates(DATA,state.calc||calculateProject(state.project),state.project);return c.find(x=>x.variant.id===id)}
function scrollTarget(id){const el=document.getElementById(id);if(el instanceof HTMLDetailsElement)el.open=true;el?.scrollIntoView({behavior:'smooth',block:'start'})}

function updateProductResults(){const rows=productRows(DATA,state.productFilters);const el=$('#product-results');if(el)el.innerHTML=productTable(rows);const title=[...document.querySelectorAll('.section-title h2')].find(x=>x.textContent.startsWith('검색 결과'));if(title)title.textContent=`검색 결과 ${rows.length}건`}
function updateSupplierResults(){const q=state.supplierQuery.toLowerCase(),rows=DATA.suppliers.filter(s=>[s.name,s.region,s.related_manufacturer_name,s.address].filter(Boolean).join(' ').toLowerCase().includes(q));const el=$('#supplier-results');if(el)el.innerHTML=supplierCards(rows)}

document.addEventListener('input',e=>{const t=e.target;if(!(t instanceof HTMLInputElement||t instanceof HTMLSelectElement))return;if(t.dataset.projectPath){let val=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;setPath(state.project,t.dataset.projectPath,val);markDirty();if(t.dataset.rerender==='1')render()}if(t.dataset.productFilter){const k=t.dataset.productFilter;state.productFilters[k]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;if(k==='frequency'&&t.value!=='all')state.productFilters[k]=Number(t.value);updateProductResults()}if(t.dataset.supplierFilter){state.supplierQuery=t.value;updateSupplierResults()}})
document.addEventListener('change',e=>{const t=e.target;if(t instanceof HTMLSelectElement&&t.dataset.projectPath){let val=t.value;if(['environment.frequencyHz','environment.voltageV'].includes(t.dataset.projectPath))val=Number(val);setPath(state.project,t.dataset.projectPath,val);markDirty();if(t.dataset.rerender==='1')render()}if(t instanceof HTMLSelectElement&&t.dataset.productFilter){state.productFilters[t.dataset.productFilter]=t.value==='all'?'all':(['frequency'].includes(t.dataset.productFilter)?Number(t.value):t.value);updateProductResults()}})
document.addEventListener('click',async e=>{const target=e.target.closest('[data-route],[data-tab],[data-action]');if(!target)return;if(target.dataset.route){location.hash=`#/${target.dataset.route}`;return}if(target.dataset.tab){state.project.tab=target.dataset.tab;markDirty();render();return}const a=target.dataset.action;if(!a)return;target.closest('.top-report-menu')?.removeAttribute('open');
  if(a==='theme'){state.theme=state.theme==='system'?'light':state.theme==='light'?'dark':'system';setTheme(state.theme);render()}
  else if(a==='scroll-inputs')$('#selector-inputs')?.scrollIntoView({behavior:'smooth'})
  else if(a==='scroll-results')scrollTarget('result-summary')
  else if(a==='scroll-candidates')scrollTarget('result-candidates')
  else if(a==='scroll-pipes')scrollTarget('result-pipes')
  else if(a==='scroll-formulas')scrollTarget('result-formulas')
  else if(a==='scroll-report')scrollTarget('report-sheet')
  else if(a==='report-settings')showReportSettings()
  else if(a==='share')shareCurrent()
  else if(a==='calculate'){state.calc=calculateProject(state.project);state.calcStamp=state.project.updatedAt;render();requestAnimationFrame(()=>$('#selection-results')?.scrollIntoView({behavior:'smooth',block:'start'}))}
  else if(a==='add-branch'){state.project.duct.branches.push({id:uid('b'),name:`가지관 ${state.project.duct.branches.length+1}`,outletCount:1,flowEachM3Min:2,lengthM:5,terminalPressureKpa:10,targetVelocityMs:18,elbows:2,tees:0,otherK:1});markDirty();render()}
  else if(a==='remove-branch'){const i=Number(target.dataset.index);if(state.project.duct.branches.length>1){state.project.duct.branches.splice(i,1);markDirty();render()}}
  else if(a==='select-candidate'){state.project.selectedVariantId=target.dataset.id;save(storage.project,state.project);render()}
  else if(a==='candidate-detail')showCandidateDetail(candidateById(target.dataset.id))
  else if(a==='save-report')saveCurrentReport()
  else if(a==='export-json')exportCurrentJson()
  else if(a==='export-html')exportCurrentHtml()
  else if(a==='export-png')exportCurrentPng()
  else if(a==='export-pdf')exportCurrentPdf()
  else if(a==='print')window.print()
  else if(a==='favorite'){const id=target.dataset.id;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save(storage.favorites,state.favorites);target.classList.toggle('on');toast(target.classList.contains('on')?'즐겨찾기에 추가했습니다.':'즐겨찾기에서 제거했습니다.')}
  else if(a==='compare-toggle'){const id=target.dataset.id;if(target.checked)state.compareIds.length<4&&state.compareIds.push(id);else state.compareIds=state.compareIds.filter(x=>x!==id);render()}
  else if(a==='open-compare'){state.compareOpen=true;render()}
  else if(a==='close-compare'){state.compareOpen=false;render()}
  else if(a==='load-report'){const r=state.reports.find(x=>x.id===target.dataset.id);if(r){state.project=ensureProject(clone(r.project));state.calc=r.calculation;state.calcStamp=state.project.updatedAt;save(storage.project,state.project);location.hash='#/selector';toast('저장된 계산 조건을 불러왔습니다.')}}
  else if(a==='delete-report'){state.reports=state.reports.filter(x=>x.id!==target.dataset.id);save(storage.reports,state.reports);render();toast('리포트를 삭제했습니다.')}
  else if(a==='import-reports')importReportsBackup()
  else if(a==='export-all-reports')download('blowerfit-reports-backup.json',JSON.stringify({exportedAt:now(),reports:state.reports},null,2),'application/json;charset=utf-8')
})

function showReportSettings(){
  const labels=[
    ['candidate','선정 후보','기본 포함','선정한 모델과 P-Q 검증 상태'],
    ['pipeSchedule','배관 Schedule','기본 포함','주배관·가지관 권장 규격'],
    ['warnings','최종 주의사항','기본 포함','P-Q 및 현장 검증 주의'],
    ['formulas','계산식 상세','선택 추가','공식·대입값·계산 결과'],
    ['inputSummary','입력 / 설계 기준','선택 추가','원 풍량·원 압력·전원조건'],
    ['environment','환경조건 / 여유율','선택 추가','온도·고도·습도·공기밀도'],
    ['sources','모델 데이터 출처','선택 추가','카탈로그/검증 상태'],
    ['suppliers','한국 공급처','선택 추가','선정 모델의 공급/문의 채널']
  ];
  const box=document.createElement('div');box.className='modal-backdrop report-settings-backdrop';
  const opts=reportOpts();
  box.innerHTML=`<div class="modal report-settings-modal" role="dialog" aria-modal="true" aria-labelledby="report-settings-title"><div class="modal-head"><div><h3 id="report-settings-title">보고서 구성</h3><small>기본 보고서는 간결하게, 필요한 항목만 체크해서 추가합니다.</small></div><button class="icon-btn" data-local-action="close" aria-label="닫기">×</button></div><div class="modal-body"><div class="report-profile-note"><b>기본 보고서</b><span>설계 Duty + 선정 후보 + 배관표 + 최종 주의사항</span></div><div class="report-option-grid">${labels.map(([key,label,tone,desc])=>`<label class="report-option"><input type="checkbox" data-report-option="${key}" ${opts[key]?'checked':''}><span><b>${label}</b><small>${tone} · ${desc}</small></span></label>`).join('')}</div><div class="modal-actions"><button class="btn btn-ghost" data-local-action="reset">기본 구성으로</button><button class="btn btn-primary" data-local-action="apply">적용하고 미리보기</button></div></div></div>`;
  document.body.appendChild(box);
  box.addEventListener('change',e=>{const t=e.target;if(t instanceof HTMLInputElement&&t.dataset.reportOption){state.project.reportOptions[t.dataset.reportOption]=t.checked;save(storage.project,state.project)}});
  box.addEventListener('click',e=>{const a=e.target.closest('[data-local-action]')?.dataset.localAction;if(e.target===box||a==='close'){box.remove();return}if(a==='reset'){state.project.reportOptions={...REPORT_DEFAULTS};save(storage.project,state.project);box.remove();render();toast('보고서 구성을 기본값으로 되돌렸습니다.');return}if(a==='apply'){save(storage.project,state.project);box.remove();render();requestAnimationFrame(()=>scrollTarget('report-sheet'));toast('보고서 구성을 적용했습니다.')}})
}

async function importReportsBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const incoming=Array.isArray(data?.reports)?data.reports:Array.isArray(data)?data:[];const valid=incoming.filter(r=>r&&r.id&&r.project&&r.calculation&&Number.isFinite(Number(r.calculation.designFlowM3Min))&&Number.isFinite(Number(r.calculation.designPressureKpa)));if(!valid.length)throw new Error('유효한 BlowerFit 리포트를 찾지 못했습니다.');const map=new Map([...valid,...state.reports].map(r=>[r.id,r]));state.reports=[...map.values()].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,50);save(storage.reports,state.reports);render();toast(`${valid.length}개 리포트를 불러왔습니다.`)}catch(err){toast(`백업 불러오기 실패: ${err.message}`)}});input.click()}

async function shareCurrent(){const u=new URL(location.href);u.searchParams.set('state',encodeShared(state.project));u.hash='#/selector';try{await navigator.clipboard.writeText(u.toString());toast('현재 입력조건 공유 링크를 복사했습니다.')}catch{prompt('공유 링크를 복사하세요.',u.toString())}}
function saveCurrentReport(){const c=state.calc||calculateProject(state.project),r={id:uid('r'),createdAt:now(),project:clone(state.project),calculation:clone(c),selectedVariantId:state.project.selectedVariantId};state.reports=[r,...state.reports].slice(0,50);save(storage.reports,state.reports);toast('현재 계산 결과를 브라우저에 저장했습니다.')}
function download(name,data,type){const b=data instanceof Blob?data:new Blob([data],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function safeName(){return(state.project.projectName||'blowerfit-report').replace(/[\\/:*?"<>|]/g,'_')}
function selectedCandidate(){return candidateById(state.project.selectedVariantId)||buildCandidates(DATA,state.calc||calculateProject(state.project),state.project).find(x=>x.endpointPass)||null}
function exportCurrentJson(){download(`${safeName()}.json`,JSON.stringify({project:state.project,calculation:state.calc,selected:selectedCandidate()},null,2),'application/json;charset=utf-8');toast('JSON 데이터를 저장했습니다.')}
function exportCurrentHtml(){
  const c=state.calc||calculateProject(state.project),s=selectedCandidate();
  const sheet=reportSheet(c,s).replace(/<button class="report-config-btn"[^>]*>.*?<\/button>/,'');
  const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(state.project.projectName)} · BlowerFit KR</title><style>body{font-family:Arial,"Noto Sans KR",sans-serif;background:#eef3f5;color:#17232b;margin:0;padding:32px}.report-sheet{max-width:980px;margin:auto;background:#fff;padding:42px;border-radius:18px}.report-head{display:flex;justify-content:space-between;border-bottom:2px solid #0b5e75;padding-bottom:14px}.report-head>div{display:flex;gap:10px;align-items:center}.report-logo{background:#0b5e75;color:white;padding:10px;border-radius:8px;font-weight:700}.report-head b,.report-head small{display:block}.report-title-row{display:flex;justify-content:space-between}.report-kpis,.report-info-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.report-kpis div,.report-info-grid div{background:#eef4f6;padding:14px;border-radius:10px}.report-kpis span,.report-info-grid span{display:block;color:#65727b;font-size:12px}.report-kpis b,.report-info-grid b{display:block;margin-top:5px}.report-selected{background:#e7f4f7;border-left:4px solid #0b5e75;padding:14px 18px;border-radius:0 10px 10px 0}table{border-collapse:collapse;width:100%}th,td{border:1px solid #dbe3e7;padding:8px;text-align:left;font-size:12px}.report-formula-cards{display:grid;gap:10px}.report-formula-cards article{display:grid;grid-template-columns:28px 1fr;gap:10px;padding:12px;border:1px solid #dbe3e7;border-radius:10px}.report-formula-cards article>span{width:28px;height:28px;display:grid;place-items:center;background:#e4f3f7;color:#0b5e75;border-radius:8px;font-weight:700}.report-formula-cards b,.report-formula-cards code,.report-formula-cards p,.report-formula-cards strong,.report-formula-cards small{display:block;margin:0 0 5px}.report-formula-cards code{white-space:normal;overflow-wrap:anywhere;color:#0b5e75}.report-warning-box{background:#fff5de;padding:16px;border-radius:12px;margin-top:24px}.report-source-box{background:#f4f7f9;padding:14px;border-radius:10px}.report-supplier-list div{padding:7px 0;border-top:1px solid #dbe3e7}.report-supplier-list b,.report-supplier-list span{display:block}.report-foot{border-top:1px solid #dbe3e7;margin-top:24px;padding-top:14px;color:#65727b}@media(max-width:700px){body{padding:10px}.report-sheet{padding:20px}.report-kpis,.report-info-grid{grid-template-columns:1fr 1fr}}</style></head><body>${sheet}</body></html>`;
  download(`${safeName()}.html`,html,'text/html;charset=utf-8');toast('HTML 보고서를 저장했습니다.')
}

function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function wrapCanvasLines(ctx,text,maxW){const paras=String(text??'').split(/\n/),out=[];for(const para of paras){if(!para){out.push('');continue}let line='';for(const ch of para){const test=line+ch;if(ctx.measureText(test).width>maxW&&line){out.push(line.trimEnd());line=ch}else line=test}if(line)out.push(line.trimEnd())}return out}
function drawWrap(ctx,text,x,y,maxW,lineH,maxLines=99){const lines=wrapCanvasLines(ctx,text,maxW).slice(0,maxLines);for(const line of lines){ctx.fillText(line,x,y);y+=lineH}return y}
function makePage(){const c=document.createElement('canvas');c.width=1240;c.height=1754;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);return{canvas:c,x}}
function canvasHeader(x,subtitle='Industrial Blower Engineering Report'){x.fillStyle='#0b5e75';x.fillRect(0,0,1240,155);x.fillStyle='#fff';x.font='700 42px sans-serif';x.fillText('BlowerFit KR',70,70);x.font='24px sans-serif';x.fillText(subtitle,70,112)}
function canvasSection(x,title,y){x.fillStyle='#17232b';x.font='700 25px sans-serif';x.fillText(title,70,y);return y+35}
function canvasInfoRow(x,items,y){const w=(1100-(items.length-1)*12)/items.length;items.forEach((it,i)=>{const xx=70+i*(w+12);x.fillStyle='#eef4f6';roundRect(x,xx,y,w,82,14);x.fill();x.fillStyle='#65727b';x.font='15px sans-serif';x.fillText(it[0],xx+14,y+27);x.fillStyle='#17232b';x.font='700 18px sans-serif';drawWrap(x,it[1],xx+14,y+54,w-28,22,2)});return y+102}
function drawPipeCanvas(x,c,y,limit=7,startIndex=0){x.font='16px sans-serif';x.fillStyle='#65727b';x.fillText('구간',80,y);x.fillText('풍량 m³/min',390,y);x.fillText('권장관경',650,y);x.fillText('경로압력 kPa',900,y);y+=18;x.strokeStyle='#d8e3e8';x.beginPath();x.moveTo(70,y);x.lineTo(1170,y);x.stroke();let rows=[{name:'주배관',flowM3Min:c.designFlowM3Min,selectedStandardDiameterMm:c.selectedMainStandardDiameterMm,pathPressureKpa:c.rawPressureKpa},...c.branchResults];if(startIndex>0)rows=rows.slice(startIndex);rows=rows.slice(0,limit);for(const b of rows){y+=36;x.fillStyle='#17232b';x.font='17px sans-serif';x.fillText(String(b.name).slice(0,28),80,y);x.fillText(f(b.flowM3Min,3),390,y);x.fillText(`Ø${b.selectedStandardDiameterMm} mm`,650,y);x.fillText(f(b.pathPressureKpa,3),900,y)}return y+18}
function reportSummaryCanvas(c,s,o){const {canvas,x}=makePage();canvasHeader(x);x.fillStyle='#17232b';x.font='700 40px sans-serif';let y=drawWrap(x,state.project.projectName,70,220,1100,48,2);x.font='20px sans-serif';x.fillStyle='#65727b';x.fillText(new Date().toLocaleString('ko-KR'),70,y+10);y=Math.max(315,y+55);const kpis=[['설계 풍량',`${c.designFlowM3Min.toFixed(3)} m³/min`],['설계 압력',`${c.designPressureKpa.toFixed(3)} kPa`],['주배관',`Ø${c.selectedMainStandardDiameterMm} mm`],['모터 예비',`${c.estimatedMotorPowerKw.toFixed(2)} kW`]];kpis.forEach((k,i)=>{const xx=70+i*275;x.fillStyle='#eef4f6';roundRect(x,xx,y,250,110,16);x.fill();x.fillStyle='#65727b';x.font='18px sans-serif';x.fillText(k[0],xx+18,y+33);x.fillStyle='#0b5e75';x.font='700 27px sans-serif';drawWrap(x,k[1],xx+18,y+75,214,30,2)});y+=150;if(o.candidate&&s){x.fillStyle='#e7f4f7';roundRect(x,70,y,1100,142,16);x.fill();x.fillStyle='#0b5e75';x.font='700 18px sans-serif';x.fillText('선정 후보',92,y+32);x.fillStyle='#17232b';x.font='700 27px sans-serif';drawWrap(x,`${s.manufacturer.name} · ${s.model.model_name}`,92,y+68,1020,31,2);x.font='18px sans-serif';x.fillStyle='#65727b';drawWrap(x,`${f(s.variant.motor_kw)} kW · ${f(s.variant.max_airflow_m3_min)} m³/min · ${f(s.variant.discharge_pressure_kpa??s.variant.vacuum_kpa)} kPa · ${s.curveStatus==='verified'?'P-Q 검증':'P-Q 검증 필요'}`,92,y+116,1020,22,2);y+=177}if(o.pipeSchedule){y=canvasSection(x,'배관 / 가지관 Schedule',y);y=drawPipeCanvas(x,c,y,7);if(c.branchResults.length>6){x.fillStyle='#65727b';x.font='14px sans-serif';x.fillText(`※ 추가 가지관 ${c.branchResults.length-6}개는 상세 부록 또는 HTML 보고서에서 확인`,80,y+12);y+=32}}const warnY=Math.max(1450,Math.min(y+45,1550));if(o.warnings){x.fillStyle='#fff5de';roundRect(x,70,warnY,1100,135,14);x.fill();x.fillStyle='#7a5200';x.font='700 17px sans-serif';x.fillText('최종 발주 전 확인',90,warnY+34);x.font='15px sans-serif';drawWrap(x,'최대풍량과 최대풍압은 같은 운전점이 아닙니다. 실제 배관·필터·노즐 조건과 제조사 공식 P-Q 곡선에서 Duty point를 반드시 확인하세요.',90,warnY+67,1050,22,4)}x.fillStyle='#65727b';x.font='14px sans-serif';x.fillText('Generated by BlowerFit KR · 예비 엔지니어링 선정용',70,1710);return canvas}
function reportDetailCanvases(c,s,o){
  const need=o.formulas||o.inputSummary||o.environment||o.sources||o.suppliers||(o.pipeSchedule&&c.branchResults.length>6);if(!need)return [];
  const pages=[];let x,y,pageNo=0;
  function begin(title='상세 계산 / 조건 부록'){const p=makePage();pages.push(p.canvas);x=p.x;pageNo+=1;canvasHeader(x,'Engineering Detail Appendix');x.fillStyle='#17232b';x.font='700 34px sans-serif';x.fillText(title,70,215);x.fillStyle='#65727b';x.font='17px sans-serif';x.fillText(`${state.project.projectName} · ${pageNo} / 상세`,70,250);x.font='14px sans-serif';x.fillText('BlowerFit KR · Detail Appendix',70,1710);y=305}
  function room(h,title='상세 계산 / 조건 부록 (계속)'){if(y+h>1600)begin(title)}
  begin();
  if(o.inputSummary){room(150);y=canvasSection(x,'입력 / 설계 기준',y);y=canvasInfoRow(x,[['선정 기준',TABDEF.find(v=>v[0]===state.project.tab)?.[2]||state.project.tab],['원 계산 풍량',`${c.rawFlowM3Min.toFixed(3)} m³/min`],['원 요구압력',`${c.rawPressureKpa.toFixed(3)} kPa`],['전원',`${state.project.environment.frequencyHz} Hz / ${state.project.environment.voltageV} V`]],y);y+=15}
  if(o.environment){room(150);y=canvasSection(x,'환경조건 / 여유율',y);const e=state.project.environment;y=canvasInfoRow(x,[['온도',`${f(e.temperatureC,1)} °C`],['고도',`${f(e.altitudeM,0)} m`],['상대습도',`${f(e.relativeHumidityPct,0)} %`],['공기밀도',`${c.airDensityKgM3.toFixed(4)} kg/m³`]],y);y+=15}
  if(o.formulas){room(70,'계산식 상세');y=canvasSection(x,'계산식 상세',y);for(const [i,st] of c.formulas.entries()){x.font='15px monospace';const fl=wrapCanvasLines(x,st.formula,1060).length;x.font='14px sans-serif';const sl=wrapCanvasLines(x,`${st.substitution} → ${st.result}`,1060).length;const h=Math.max(116,55+Math.min(fl,4)*20+Math.min(sl,4)*19+(st.note?22:0));room(h+12,'계산식 상세 (계속)');x.fillStyle='#f4f8f9';roundRect(x,70,y,1100,h,12);x.fill();x.fillStyle='#0b5e75';x.font='700 17px sans-serif';x.fillText(`${i+1}. ${st.label}`,88,y+28);x.fillStyle='#17232b';x.font='15px monospace';let yy=drawWrap(x,st.formula,88,y+54,1060,20,4);x.font='14px sans-serif';x.fillStyle='#566771';yy=drawWrap(x,`${st.substitution} → ${st.result}`,88,yy+2,1060,19,4);if(st.note){x.font='13px sans-serif';x.fillStyle='#7b8790';drawWrap(x,`※ ${st.note}`,88,yy+3,1060,18,2)}y+=h+10}}
  if(o.pipeSchedule&&c.branchResults.length>6){room(380,'배관 상세 부록');y=canvasSection(x,'추가 가지관',y+5);let start=7;while(start<1+c.branchResults.length){room(340,'배관 상세 부록 (계속)');y=drawPipeCanvas(x,c,y,8,start);start+=8;if(start<1+c.branchResults.length)y+=20}}
  if(o.sources||o.suppliers){room(250,'출처 / 구매 연결');y=canvasSection(x,'출처 / 구매 연결',y+10);if(s){x.fillStyle='#17232b';x.font='15px sans-serif';y=drawWrap(x,`모델 데이터: ${s.model.source_document||s.variant.source_page_or_section||'등록 데이터'}`,80,y,1080,22,4);y=drawWrap(x,`검증 상태: ${s.curveStatus==='verified'?'P-Q 검증됨':'공식 P-Q 운전점 확인 필요'}`,80,y+4,1080,22,2);if(o.suppliers&&s.suppliers?.length){for(const sp of s.suppliers.slice(0,8)){room(55,'구매 연결 (계속)');y=drawWrap(x,`• ${sp.name} / ${sp.region||'한국'} / ${sp.phone||sp.email||'공식 문의채널'}`,90,y+7,1060,20,3)}}}else{x.fillStyle='#65727b';x.font='15px sans-serif';x.fillText('선정 후보가 없어 출처/구매처를 표시하지 않았습니다.',80,y)}}
  return pages
}
function makeReportCanvases(){const c=state.calc||calculateProject(state.project),s=selectedCandidate(),o=reportOpts();return [reportSummaryCanvas(c,s,o),...reportDetailCanvases(c,s,o)]}

function combineCanvases(pages){if(pages.length===1)return pages[0];const gap=40,c=document.createElement('canvas');c.width=pages[0].width;c.height=pages.reduce((sum,p)=>sum+p.height,0)+gap*(pages.length-1);const x=c.getContext('2d');x.fillStyle='#e8eef1';x.fillRect(0,0,c.width,c.height);let y=0;for(const p of pages){x.drawImage(p,0,y);y+=p.height+gap}return c}
function exportCurrentPng(){const c=combineCanvases(makeReportCanvases());c.toBlob(b=>{if(b)download(`${safeName()}.png`,b,'image/png')},'image/png');toast('PNG 보고서를 저장했습니다.')}
function dataUrlBytes(url){const b=atob(url.split(',')[1]),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
function concatBytes(arr){const len=arr.reduce((s,a)=>s+a.length,0),out=new Uint8Array(len);let o=0;for(const a of arr){out.set(a,o);o+=a.length}return out}
function ascii(s){return new TextEncoder().encode(s)}
function canvasPdfBlob(canvases){const pages=Array.isArray(canvases)?canvases:[canvases],w=595.28,h=841.89,objects=[null,null],kids=[];for(let i=0;i<pages.length;i++){const pageObj=3+i*3,contentObj=pageObj+1,imageObj=pageObj+2;kids.push(`${pageObj} 0 R`);const jpg=dataUrlBytes(pages[i].toDataURL('image/jpeg',.92)),content=`q\n${w} 0 0 ${h} 0 0 cm\n/Im0 Do\nQ\n`;objects[pageObj]=ascii(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im0 ${imageObj} 0 R >> >> /Contents ${contentObj} 0 R >>`);objects[contentObj]=concatBytes([ascii(`<< /Length ${content.length} >>\nstream\n`),ascii(content),ascii('endstream')]);objects[imageObj]=concatBytes([ascii(`<< /Type /XObject /Subtype /Image /Width ${pages[i].width} /Height ${pages[i].height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`),jpg,ascii('\nendstream')])}objects[1]=ascii('<< /Type /Catalog /Pages 2 0 R >>');objects[2]=ascii(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${pages.length} >>`);let parts=[ascii('%PDF-1.4\n%\xFF\xFF\xFF\xFF\n')],offsets=[0],pos=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=pos;const obj=concatBytes([ascii(`${i} 0 obj\n`),objects[i],ascii('\nendobj\n')]);parts.push(obj);pos+=obj.length}const xref=pos;let table=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)table+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;parts.push(ascii(table+`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return new Blob([concatBytes(parts)],{type:'application/pdf'})}
function exportCurrentPdf(){const pages=makeReportCanvases();download(`${safeName()}.pdf`,canvasPdfBlob(pages),'application/pdf');toast(`PDF 보고서를 ${pages.length}페이지로 저장했습니다.`)}

function showCandidateDetail(c){if(!c)return;const pressure=c.variant.discharge_pressure_kpa??c.variant.vacuum_kpa,sup=c.suppliers.map(s=>{const site=s.website||s.source_url,subject=`[BlowerFit RFQ] ${c.model.model_name} 블로워 견적 요청`,body=`안녕하세요.\n\n아래 조건으로 블로워 견적 및 공식 P-Q 운전점 검토를 요청드립니다.\n- 모델 후보: ${c.manufacturer.name} / ${c.model.model_name}\n- 설계 풍량: ${(state.calc||calculateProject(state.project)).designFlowM3Min.toFixed(3)} m³/min\n- 설계 압력/진공: ${(state.calc||calculateProject(state.project)).designPressureKpa.toFixed(3)} kPa\n- 주파수: ${state.project.environment.frequencyHz} Hz\n- 전압: ${state.project.environment.voltageV} V\n- 프로젝트: ${state.project.projectName}\n\n최종 운전점 성능, 모터 정격, 연결 규격, 납기 및 견적을 부탁드립니다.`;return `<div class="supplier-link-row"><b>${esc(s.name)} · ${esc(s.region||'')}</b>${site?`<a href="${esc(site)}" target="_blank" rel="noreferrer">공식 사이트 ↗</a>`:''}${s.email?`<a href="mailto:${esc(s.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}">RFQ 이메일</a>`:''}</div>`}).join('')||'<p>현재 seed에 공식 한국 공급처 연결이 없습니다.</p>';const box=document.createElement('div');box.className='modal-backdrop';box.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div class="modal-head"><h3 id="detail-title">${esc(c.manufacturer.name)} · ${esc(c.model.model_name)}</h3><button class="icon-btn" id="detail-close" aria-label="상세창 닫기">×</button></div><div class="modal-body"><div class="detail-grid"><div class="detail-spec"><h4>카탈로그 endpoint</h4><dl><dt>모터</dt><dd>${f(c.variant.motor_kw)} kW / ${f(c.variant.motor_hp)} HP</dd><dt>최대풍량</dt><dd>${f(c.variant.max_airflow_m3_min,3)} m³/min</dd><dt>압력/진공</dt><dd>${f(pressure,3)} kPa</dd><dt>주파수</dt><dd>${f(c.variant.frequency_hz,0)} Hz</dd><dt>소음</dt><dd>${f(c.variant.sound_dba)} dB(A)</dd><dt>중량</dt><dd>${f(c.variant.weight_kg)} kg</dd></dl></div><div class="detail-spec"><h4>현재 설계 대비</h4><dl><dt>풍량 여유</dt><dd>${c.flowRatio?c.flowRatio.toFixed(2)+'×':'—'}</dd><dt>압력 여유</dt><dd>${c.pressureRatio?c.pressureRatio.toFixed(2)+'×':'—'}</dd><dt>후보 점수</dt><dd>${c.score}</dd><dt>검증 상태</dt><dd>${c.curveStatus}</dd></dl></div><div class="detail-reasons"><h4>판단 근거</h4><ul>${c.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div><div class="detail-source"><h4>출처/구매</h4><p>${esc(c.model.source_document||c.variant.source_page_or_section||'출처 데이터')}</p>${sup}</div><div class="callout warn"><b>중요</b><span>최대풍량과 최대풍압은 같은 운전점이 아닙니다. 최종 발주 전 공식 P-Q 곡선에서 현재 설계점 통과 여부를 확인하세요.</span></div></div></div></div>`;document.body.appendChild(box);box.addEventListener('click',e=>{if(e.target===box||e.target.id==='detail-close')box.remove()})}

init()
