export const STANDARD_PIPE_MM=[20,25,32,40,50,65,80,90,100,125,150,175,200,225,250,300,350,400,450,500,600]
const G=9.80665,RD=287.058,RV=461.495
export const clamp=(v,min,max)=>Math.min(max,Math.max(min,v))
export function atmosphericPressurePa(alt){const h=clamp(Number(alt)||0,-500,11000);return 101325*Math.pow(1-2.25577e-5*h,5.25588)}
export function saturationVaporPressurePa(t){return 610.94*Math.exp((17.625*t)/(t+243.04))}
export function airDensityKgM3(env){const tK=env.temperatureC+273.15,p=atmosphericPressurePa(env.altitudeM),pv=saturationVaporPressurePa(env.temperatureC)*clamp(env.relativeHumidityPct/100,0,1),pd=Math.max(1000,p-pv);return pd/(RD*tK)+pv/(RV*tK)}
export function dynamicViscosityPaS(t){const T=t+273.15;return 1.716e-5*Math.pow(T/273.15,1.5)*((273.15+111)/(T+111))}
export function circularAreaM2(mm){const d=mm/1000;return Math.PI*d*d/4}
export function openingAreaM2(i){const w=i.widthMm/1000,h=i.heightMm/1000,l=i.lengthMm/1000,d=i.diameterMm/1000;switch(i.shape){case'circle':return Math.PI*d*d/4;case'rectangle':return Math.max(0,w*h);case'slot':return Math.max(0,l*h);case'oblong':{const minor=Math.min(w,l),major=Math.max(w,l);return Math.max(0,minor*Math.max(0,major-minor)+Math.PI*minor*minor/4)}default:return 0}}
export function equivalentRoundDiameterMm(flow,targetV){const q=Math.max(flow,0)/60,v=Math.max(targetV,.1);return Math.sqrt(4*q/(Math.PI*v))*1000}
export function nextStandardDiameterMm(required){return STANDARD_PIPE_MM.find(d=>d>=required)??Math.ceil(required/50)*50}
export function velocityInRoundPipeMs(flow,dmm){return (Math.max(flow,0)/60)/circularAreaM2(Math.max(dmm,1))}
export function reynoldsNumber(rho,v,d,mu){return rho*Math.abs(v)*d/Math.max(mu,1e-9)}
export function frictionFactorSwameeJain(re,rough,d){if(re<=0)return 0;if(re<2300)return 64/re;const term=Math.max(0,rough)/Math.max(d,1e-6)/3.7+5.74/Math.pow(re,.9);return .25/Math.pow(Math.log10(term),2)}
export function pipeLossKpa(i){const d=Math.max(i.diameterMm,1)/1000,v=velocityInRoundPipeMs(i.flowM3Min,i.diameterMm),re=reynoldsNumber(i.rho,v,d,i.mu),f=frictionFactorSwameeJain(re,(i.roughnessMm??.15)/1000,d),qd=.5*i.rho*v*v,fr=f*(Math.max(i.lengthM,0)/d)*qd,k=(i.elbows??0)*.75+(i.tees??0)*1.5+(i.otherK??0),local=Math.max(0,k)*qd;return{velocityMs:v,reynolds:re,frictionFactor:f,frictionLossKpa:fr/1000,localLossKpa:local/1000,totalLossKpa:(fr+local)/1000}}
export function terminalPressureForVelocityKpa(v,rho,cd=.9){return .5*rho*Math.pow(Math.max(v,0)/clamp(cd,.2,1),2)/1000}
function motorEstimateKw(q,p,eta=.58){const air=Math.max(q,0)/60*Math.max(p,0);return{airKw:air,motorKw:air/clamp(eta,.25,.9)*1.1}}
function recommendedTypes(flow,pressure,app){const a=[];if(pressure<=50&&flow<=40)a.push('링/사이드채널 블로워');if(pressure>=20&&flow>=10)a.push('루츠/PD 블로워');if(pressure<=150&&flow>=20)a.push('터보/원심 블로워');if(pressure>=50)a.push('스크류 블로워');if(['air_knife','plating','wash_drying','film_web'].includes(app))a.unshift('링/사이드채널 또는 고속 원심 블로워');return[...new Set(a)].slice(0,4)}
function equalBranches(total,count,length,targetV,elbows,terminalP,env,rough){const n=Math.max(1,Math.round(count)),rho=airDensityKgM3(env),mu=dynamicViscosityPaS(env.temperatureC),raw=total/n,design=raw*(1+env.flowMarginPct/100),ideal=equivalentRoundDiameterMm(design,targetV),std=nextStandardDiameterMm(ideal);return Array.from({length:n},(_,x)=>{const loss=pipeLossKpa({flowM3Min:design,lengthM:length,diameterMm:std,elbows,roughnessMm:rough,rho,mu});return{id:`branch-${x+1}`,name:`가지관 ${x+1}`,flowM3Min:raw,recommendedDiameterMm:ideal,selectedStandardDiameterMm:std,actualVelocityMs:loss.velocityMs,frictionLossKpa:loss.frictionLossKpa,localLossKpa:loss.localLossKpa,terminalPressureKpa:terminalP,pathPressureKpa:terminalP+loss.totalLossKpa}})}
function finalize(mode,rawFlow,terminalP,branches,env,pipe,formulas,warnings,notes,app,branchLossOverride=null){const rho=airDensityKgM3(env),mu=dynamicViscosityPaS(env.temperatureC),designFlow=rawFlow*(1+Math.max(env.flowMarginPct,0)/100),ideal=equivalentRoundDiameterMm(designFlow,pipe.mainTargetVelocityMs),std=nextStandardDiameterMm(ideal),main=pipeLossKpa({flowM3Min:designFlow,lengthM:pipe.mainLengthM,diameterMm:std,elbows:pipe.mainElbows,tees:pipe.mainTees,otherK:pipe.otherLocalK,roughnessMm:pipe.roughnessMm,rho,mu});
  const worstBranchLoss=branchLossOverride!=null?branchLossOverride:(branches.length?Math.max(...branches.map(b=>b.frictionLossKpa+b.localLossKpa)):0),rawP=terminalP+worstBranchLoss+main.totalLossKpa+Math.max(pipe.filterLossKpa,0),designP=rawP*(1+Math.max(env.pressureMarginPct,0)/100),pow=motorEstimateKw(designFlow,designP);
  formulas.push({label:'설계 풍량',formula:'Qdesign = Qraw × (1 + 유량 여유율)',substitution:`${rawFlow.toFixed(3)} × ${(1+env.flowMarginPct/100).toFixed(3)}`,result:`${designFlow.toFixed(3)} m³/min`},{label:'주배관 이론 내경',formula:'D = √(4Q / πv)',substitution:`Q=${(designFlow/60).toFixed(4)} m³/s, v=${pipe.mainTargetVelocityMs.toFixed(1)} m/s`,result:`${ideal.toFixed(1)} mm → 표준 ${std} mm`},{label:'주배관 압력손실',formula:'ΔP = f(L/D)(ρv²/2) + K(ρv²/2)',substitution:`f=${main.frictionFactor.toFixed(4)}, Re=${main.reynolds.toFixed(0)}, v=${main.velocityMs.toFixed(2)} m/s`,result:`${main.totalLossKpa.toFixed(3)} kPa`,note:'예비 K: 90° 엘보 0.75, T 1.5. 실제 피팅 형상에 따라 조정'},{label:'설계 풍압',formula:'Pdesign = (Pterminal + Pbranch + Pmain + Pfilter) × (1 + 압력 여유율)',substitution:`(${terminalP.toFixed(3)} + ${worstBranchLoss.toFixed(3)} + ${main.totalLossKpa.toFixed(3)} + ${pipe.filterLossKpa.toFixed(3)}) × ${(1+env.pressureMarginPct/100).toFixed(3)}`,result:`${designP.toFixed(3)} kPa`},{label:'공기동력/모터 예비값',formula:'Pair = Q·ΔP, Pmotor ≈ Pair/η × 1.10',substitution:'η=0.58 예비 가정',result:`공기동력 ${pow.airKw.toFixed(2)} kW / 모터 ${pow.motorKw.toFixed(2)} kW`});
  if(main.velocityMs>30)warnings.push('주배관 유속이 30 m/s를 초과합니다. 관경 상향을 검토하세요.');if(designP>80)warnings.push('설계 차압이 80 kPa를 초과합니다. PD/스크류/다단 압축 방식을 함께 검토하세요.');
  return{mode,valid:designFlow>0&&designP>=0,warnings,airDensityKgM3:rho,dynamicViscosityPaS:mu,rawFlowM3Min:rawFlow,designFlowM3Min:designFlow,rawPressureKpa:rawP,designPressureKpa:designP,recommendedMainDiameterMm:ideal,selectedMainStandardDiameterMm:std,mainActualVelocityMs:main.velocityMs,mainFrictionLossKpa:main.frictionLossKpa,mainLocalLossKpa:main.localLossKpa,filterLossKpa:pipe.filterLossKpa,estimatedAirPowerKw:pow.airKw,estimatedMotorPowerKw:pow.motorKw,branchResults:branches,formulas,applicationLabel:app,recommendedTypes:recommendedTypes(designFlow,designP,app),notes}
}
export function calcFlow(i,e){const f=[{label:'입력 Duty',formula:'Qraw = 사용자 요구풍량, Pterminal = 말단 요구 정압',substitution:`Q=${i.requiredFlowM3Min} m³/min, P=${i.terminalPressureKpa} kPa`,result:'직접 입력'}],b=equalBranches(i.requiredFlowM3Min,i.branchCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,i.terminalPressureKpa,e,i.roughnessMm);return finalize('flow',i.requiredFlowM3Min,i.terminalPressureKpa,b,e,i,f,[],['풍량 기준 탭은 요구 풍량을 중심으로 배관손실과 여유율을 더합니다.'])}
export function calcPressure(i,e){const f=[{label:'입력 Duty',formula:'Pterminal = 요구풍압, Qraw = 최소 필요풍량',substitution:`P=${i.requiredPressureKpa} kPa, Q=${i.minimumFlowM3Min} m³/min`,result:'직접 입력'}],b=equalBranches(i.minimumFlowM3Min,i.branchCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,i.requiredPressureKpa,e,i.roughnessMm);return finalize('pressure',i.minimumFlowM3Min,i.requiredPressureKpa,b,e,i,f,[],['풍압 기준은 실제 P-Q 검증이 특히 중요합니다.'])}
export function calcOpenings(i,e){const f=[],w=[],rho=airDensityKgM3(e),ae=openingAreaM2(i),at=ae*Math.max(i.count,0),raw=at*Math.max(i.targetExitVelocityMs,0)*60,tp=terminalPressureForVelocityKpa(i.targetExitVelocityMs,rho,i.dischargeCoefficient);f.push({label:'개구부 총면적',formula:'Atotal=Aeach×N',substitution:`${ae.toExponential(4)}×${i.count}`,result:`${at.toFixed(6)} m²`},{label:'개구부 풍량',formula:'Q=A×v',substitution:`${at.toFixed(6)}×${i.targetExitVelocityMs}×60`,result:`${raw.toFixed(3)} m³/min`},{label:'노즐 동압',formula:'ΔP=ρ/2×(v/Cd)²',substitution:`ρ=${rho.toFixed(3)}, v=${i.targetExitVelocityMs}, Cd=${i.dischargeCoefficient}`,result:`${tp.toFixed(3)} kPa`});if(i.targetExitVelocityMs>100)w.push('출구속도 100 m/s 이상은 압축성 효과를 별도 검토하세요.');const b=equalBranches(raw,i.branchCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,tp,e,i.roughnessMm);return finalize('openings',raw,tp,b,e,i,f,w,['개구면적과 목표 분사속도 기반 예비 산정입니다.'],'air_knife')}
export function calcAirknife(i,e){const f=[],w=[],rho=airDensityKgM3(e),a=i.knifeWidthMm/1000*i.slotGapMm/1000*Math.max(i.knifeCount,0),raw=a*Math.max(i.targetExitVelocityMs,0)*60,tp=terminalPressureForVelocityKpa(i.targetExitVelocityMs,rho,i.dischargeCoefficient),t=i.lineSpeedMMin>0?(i.blowZoneLengthMm/1000)/(i.lineSpeedMMin/60):0;f.push({label:'총 슬롯면적',formula:'A=폭×간극×knife수',substitution:`${i.knifeWidthMm}mm×${i.slotGapMm}mm×${i.knifeCount}`,result:`${a.toFixed(6)} m²`},{label:'요구풍량',formula:'Q=A×v×60',substitution:`${a.toFixed(6)}×${i.targetExitVelocityMs}×60`,result:`${raw.toFixed(3)} m³/min`},{label:'슬롯 말단 동압',formula:'ΔP=ρ/2×(v/Cd)²',substitution:`ρ=${rho.toFixed(3)}, Cd=${i.dischargeCoefficient}`,result:`${tp.toFixed(3)} kPa`},{label:'블로우존 체류시간',formula:'t=Lzone/line speed',substitution:`${i.blowZoneLengthMm/1000}m / ${(i.lineSpeedMMin/60).toFixed(3)}m/s`,result:`${t.toFixed(3)} s`},{label:'분사 기하조건',formula:'이격거리·분사각은 액절단 성능 검토 변수',substitution:`standoff=${i.standoffMm??20} mm, angle=${i.angleDeg??30}°`,result:'기하조건 기록',note:'액막 두께·점도·표면장력 데이터가 없으므로 풍량/동압 식에 임의 보정계수를 적용하지 않습니다.'});if(i.slotGapMm<.3)w.push('슬롯 간극이 매우 작습니다. 막힘·가공공차·헤더 균압을 확인하세요.');if(i.targetExitVelocityMs>100)w.push('고속 제트 영역입니다. 압축성 및 소음 검토가 필요합니다.');const b=equalBranches(raw,i.knifeCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,tp,e,i.roughnessMm);return finalize('airknife',raw,tp,b,e,i,f,w,['도금 R2R은 분사각·이격거리·액 물성·라인속도와 미스트 배기를 함께 검토하세요.'],'air_knife')}
function calcBranch(b,e,rough){const rho=airDensityKgM3(e),mu=dynamicViscosityPaS(e.temperatureC),raw=Math.max(0,b.outletCount)*Math.max(0,b.flowEachM3Min),design=raw*(1+e.flowMarginPct/100),ideal=equivalentRoundDiameterMm(design,b.targetVelocityMs),std=nextStandardDiameterMm(ideal),loss=pipeLossKpa({flowM3Min:design,lengthM:b.lengthM,diameterMm:std,elbows:b.elbows,tees:b.tees,otherK:b.otherK,roughnessMm:rough,rho,mu});return{id:b.id,name:b.name,flowM3Min:raw,recommendedDiameterMm:ideal,selectedStandardDiameterMm:std,actualVelocityMs:loss.velocityMs,frictionLossKpa:loss.frictionLossKpa,localLossKpa:loss.localLossKpa,terminalPressureKpa:b.terminalPressureKpa,pathPressureKpa:b.terminalPressureKpa+loss.totalLossKpa}}
export function calcDuct(i,e){const b=i.branches.map(x=>calcBranch(x,e,i.roughnessMm)),raw=b.reduce((s,x)=>s+x.flowM3Min,0),worst=b.length?b.reduce((a,x)=>x.pathPressureKpa>a.pathPressureKpa?x:a,b[0]):null,tp=worst?.terminalPressureKpa??0,f=[{label:'분기 총풍량',formula:'Qtotal=Σ(Ni×qi)',substitution:b.map(x=>`${x.name} ${x.flowM3Min.toFixed(2)}`).join(' + '),result:`${raw.toFixed(3)} m³/min`},{label:'최악 경로',formula:'Ppath=Pterminal+Pfriction+Plocal',substitution:worst?.name??'없음',result:`${(worst?.pathPressureKpa??0).toFixed(3)} kPa`}],w=[];if(!b.length)w.push('최소 한 개의 가지관을 추가하세요.');const worstBranchLoss=worst?worst.frictionLossKpa+worst.localLossKpa:0;return finalize('duct',raw,tp,b,e,i,f,w,['주배관은 총풍량, 압력은 실제 최악 경로 가지관의 말단압력+손실 기준으로 계산합니다.'],undefined,worstBranchLoss)}
export function calcVacuum(i,e){const f=[],w=[],area=Math.max(i.cupAreaCm2,0)/10000,hold=area>0?Math.max(i.loadKg,0)*G*Math.max(i.holdingSafetyFactor,1)/area/1000:0,target=Math.max(i.targetVacuumKpa,hold),raw=Math.max(i.suctionFlowM3Min,0)*(1+Math.max(i.leakageReservePct,0)/100);f.push({label:'리프팅 요구차압',formula:'ΔP=m·g·SF/A',substitution:`m=${i.loadKg}kg, SF=${i.holdingSafetyFactor}, A=${area.toFixed(5)}m²`,result:`${hold.toFixed(3)} kPa`},{label:'누설여유 흡입풍량',formula:'Q=Qbase×(1+reserve)',substitution:`${i.suctionFlowM3Min}×${(1+i.leakageReservePct/100).toFixed(3)}`,result:`${raw.toFixed(3)} m³/min`});if(hold>i.targetVacuumKpa)w.push(`하중 기준 필요 진공도 ${hold.toFixed(1)} kPa가 더 커 이를 적용했습니다.`);const b=equalBranches(raw,i.branchCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,target,e,i.roughnessMm);return finalize('vacuum',raw,target,b,e,i,f,w,['진공 모드는 모델의 vacuum_kPa를 우선 비교합니다.'],'vacuum')}
export function calcApplication(i,e){const f=[{label:'용도 기반 Duty',formula:'공정 요구 풍량/압력 + 용도태그',substitution:`${i.application}: ${i.requiredFlowM3Min} m³/min, ${i.requiredPressureKpa} kPa`,result:'공정 Duty 적용'}],b=equalBranches(i.requiredFlowM3Min,i.branchCount,i.branchLengthM,i.branchTargetVelocityMs,i.branchElbows,i.requiredPressureKpa,e,i.roughnessMm),notes=[i.continuousDuty?'연속운전 조건: 온도·베어링·필터 서비스 주기를 보수적으로 검토':'간헐운전 조건',i.preferOilFree?'오일프리 선호 조건':'오일프리 필수 아님'];return finalize('application',i.requiredFlowM3Min,i.requiredPressureKpa,b,e,i,f,[],notes,i.application)}
export function calculateProject(p){switch(p.tab){case'flow':return calcFlow(p.flow,p.environment);case'pressure':return calcPressure(p.pressure,p.environment);case'openings':return calcOpenings(p.openings,p.environment);case'airknife':return calcAirknife(p.airknife,p.environment);case'duct':return calcDuct(p.duct,p.environment);case'vacuum':return calcVacuum(p.vacuum,p.environment);default:return calcApplication(p.application,p.environment)}}
export function defaultProject(){const c={mainLengthM:15,mainTargetVelocityMs:20,mainElbows:4,mainTees:1,filterLossKpa:1,roughnessMm:.15,otherLocalK:1};return{projectName:'도금라인 블로워 검토',tab:'airknife',environment:{temperatureC:20,altitudeM:50,relativeHumidityPct:50,flowMarginPct:15,pressureMarginPct:15,frequencyHz:60,voltageV:380},flow:{...c,requiredFlowM3Min:12,terminalPressureKpa:20,branchCount:2,branchLengthM:4,branchTargetVelocityMs:18,branchElbows:2},pressure:{...c,requiredPressureKpa:40,minimumFlowM3Min:10,branchCount:2,branchLengthM:4,branchTargetVelocityMs:18,branchElbows:2},openings:{...c,shape:'circle',diameterMm:8,widthMm:20,heightMm:2,lengthMm:30,count:20,targetExitVelocityMs:55,dischargeCoefficient:.85,branchCount:2,branchLengthM:4,branchTargetVelocityMs:18,branchElbows:2},airknife:{...c,knifeWidthMm:800,slotGapMm:1,knifeCount:2,targetExitVelocityMs:60,dischargeCoefficient:.92,lineSpeedMMin:10,blowZoneLengthMm:120,standoffMm:20,angleDeg:30,branchLengthM:4,branchTargetVelocityMs:18,branchElbows:2},duct:{...c,branches:[{id:'b1',name:'좌측 에어나이프',outletCount:1,flowEachM3Min:4,lengthM:5,terminalPressureKpa:12,targetVelocityMs:18,elbows:2,tees:0,otherK:1},{id:'b2',name:'우측 에어나이프',outletCount:1,flowEachM3Min:4,lengthM:7,terminalPressureKpa:12,targetVelocityMs:18,elbows:3,tees:0,otherK:1}]},vacuum:{...c,targetVacuumKpa:30,suctionFlowM3Min:6,cupAreaCm2:150,loadKg:40,holdingSafetyFactor:2.5,leakageReservePct:30,branchCount:1,branchLengthM:6,branchTargetVelocityMs:18,branchElbows:2},application:{...c,application:'plating',requiredFlowM3Min:12,requiredPressureKpa:25,continuousDuty:true,preferOilFree:true,branchCount:2,branchLengthM:4,branchTargetVelocityMs:18,branchElbows:2},selectedVariantId:null,updatedAt:new Date().toISOString()}}
